# Generated by Django 3.0.2 on 2020-03-29 03:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='facebook_account',
        ),
        migrations.RemoveField(
            model_name='user',
            name='github_account',
        ),
        migrations.RemoveField(
            model_name='user',
            name='twitter_account',
        ),
    ]
