# Generated by Django 3.0.2 on 2020-04-20 23:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200329_1114'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': '网站用户'},
        ),
    ]
