# Generated by Django 3.0.2 on 2021-01-29 12:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200421_0730'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserQueryTrace',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('last_mod_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='更新时间')),
                ('query_string', models.CharField(blank=True, max_length=255, verbose_name='查询内容')),
                ('request_url', models.CharField(blank=True, max_length=255, verbose_name='请求的url')),
                ('ip_addr', models.CharField(blank=True, max_length=50, null=True, verbose_name='访问ip')),
                ('uid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户id')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserActionTrace',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('last_mod_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='更新时间')),
                ('action_name', models.CharField(blank=True, max_length=255, verbose_name='操作名称')),
                ('request_url', models.CharField(blank=True, max_length=255, verbose_name='请求的url')),
                ('ip_addr', models.CharField(blank=True, max_length=50, null=True, verbose_name='访问ip')),
                ('uid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户id')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
