# Generated by Django 3.0.2 on 2020-05-07 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investors', '0006_auto_20200429_0634'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradestrategy',
            name='is_visible',
            field=models.BooleanField(default=False, verbose_name='是否可见'),
        ),
        migrations.AlterField(
            model_name='tradestrategy',
            name='applied_period',
            field=models.CharField(blank=True, choices=[('30', '30分钟'), ('wk', '周线'), ('15', '15分钟'), ('dd', '日线'), ('mm', '月线'), ('60', '60分钟')], default='60', max_length=2, verbose_name='应用周期'),
        ),
    ]
