# Generated by Django 3.0.2 on 2020-05-08 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investors', '0009_auto_20200508_0705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tradestrategy',
            name='applied_period',
            field=models.CharField(blank=True, choices=[('wk', '周线'), ('dd', '日线'), ('15', '15分钟'), ('60', '60分钟'), ('mm', '月线'), ('30', '30分钟')], default='60', max_length=2, verbose_name='应用周期'),
        ),
    ]
