# Generated by Django 3.0.2 on 2020-05-08 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investors', '0010_auto_20200508_2040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tradestrategy',
            name='applied_period',
            field=models.CharField(blank=True, choices=[('dd', '日线'), ('60', '60分钟'), ('15', '15分钟'), ('30', '30分钟'), ('wk', '周线'), ('mm', '月线')], default='60', max_length=2, verbose_name='应用周期'),
        ),
        migrations.AlterField(
            model_name='tradestrategy',
            name='name',
            field=models.CharField(max_length=30, verbose_name='策略名'),
        ),
    ]
