# Generated by Django 3.0.2 on 2020-05-24 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investors', '0024_auto_20200523_2134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tradestrategy',
            name='applied_period',
            field=models.CharField(blank=True, choices=[('30', '30分钟'), ('60', '60分钟'), ('wk', '周线'), ('mm', '月线'), ('15', '15分钟'), ('dd', '日线')], default='60', max_length=2, null=True, verbose_name='应用周期'),
        ),
    ]
