# Generated by Django 3.0.2 on 2020-06-01 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investors', '0038_auto_20200601_1658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tradestrategy',
            name='applied_period',
            field=models.CharField(blank=True, choices=[('60', '60分钟'), ('30', '30分钟'), ('mm', '月线'), ('15', '15分钟'), ('dd', '日线'), ('wk', '周线')], default='60', max_length=2, null=True, verbose_name='应用周期'),
        ),
        migrations.AlterField(
            model_name='tradestrategy',
            name='code',
            field=models.CharField(choices=[('jiuzhuan_s', '九转序列卖点'), ('break_through', '突破阻力位'), ('shuangtou_s', '双头卖点'), ('shuangdi_b', '双底买点'), ('jiuzhuan_b', '九转序列买点'), ('stop_loss', '止损'), ('sell', '卖出'), ('take_profit', '止盈'), ('add_positions', '加仓'), ('buy', '买入'), ('fall_below', '跌破支撑位')], default='buy', max_length=50, verbose_name='策略代码'),
        ),
    ]
