# Generated by Django 3.0.2 on 2020-06-06 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investors', '0045_auto_20200604_1251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tradestrategy',
            name='applied_period',
            field=models.CharField(blank=True, choices=[('60', '60分钟'), ('30', '30分钟'), ('mm', '月线'), ('dd', '日线'), ('wk', '周线'), ('15', '15分钟')], default='60', max_length=2, null=True, verbose_name='应用周期'),
        ),
        migrations.AlterField(
            model_name='tradestrategy',
            name='code',
            field=models.CharField(blank=True, choices=[('ma25_b', 'MA25支撑位'), ('shuangtou_s', '双头卖点'), ('shuangdi_b', '双底买点'), ('diepo_s', '跌破支撑位'), ('jiuzhuan_s', '九转序列卖点'), ('tupo_b', '突破阻力位'), ('jiuzhuan_b', '九转序列买点')], max_length=50, null=True, verbose_name='策略代码'),
        ),
    ]
