# Generated by Django 3.0.2 on 2020-06-06 23:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('investors', '0046_auto_20200607_0718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tradestrategy',
            name='applied_period',
            field=models.CharField(blank=True, choices=[('mm', '月线'), ('60', '60分钟'), ('30', '30分钟'), ('dd', '日线'), ('wk', '周线'), ('15', '15分钟')], default='60', max_length=2, null=True, verbose_name='应用周期'),
        ),
        migrations.AlterField(
            model_name='tradestrategy',
            name='code',
            field=models.CharField(blank=True, choices=[('tupo_b', '突破阻力位'), ('shuangtou_s', '双头卖点'), ('ma25_b', 'MA25支撑位'), ('jiuzhuan_s', '九转序列卖点'), ('jiuzhuan_b', '九转序列买点'), ('shuangdi_b', '双底买点'), ('diepo_s', '跌破支撑位')], max_length=50, null=True, verbose_name='策略代码'),
        ),
        migrations.CreateModel(
            name='StrategyAnalysisCode',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('last_mod_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='最后更新时间')),
                ('name', models.CharField(default='', max_length=30, verbose_name='代码名称')),
                ('analysis_code', models.CharField(default='', max_length=25, verbose_name='代码编号')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
            ],
            options={
                'verbose_name': '策略分析代码',
                'verbose_name_plural': '策略分析代码',
                'ordering': ['analysis_code'],
            },
        ),
    ]
