# Generated by Django 3.0.2 on 2020-06-06 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investors', '0048_auto_20200607_0724'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tradestrategy',
            name='code',
        ),
        migrations.AddField(
            model_name='tradestrategy',
            name='category',
            field=models.CharField(blank=True, choices=[('sell_stock', '卖'), ('buy_stock', '买'), ('hold_stock', '持仓')], max_length=50, null=True, verbose_name='策略分类'),
        ),
        migrations.AlterField(
            model_name='tradestrategy',
            name='applied_period',
            field=models.CharField(blank=True, choices=[('dd', '日线'), ('30', '30分钟'), ('15', '15分钟'), ('wk', '周线'), ('mm', '月线'), ('60', '60分钟')], default='60', max_length=2, null=True, verbose_name='应用周期'),
        ),
    ]
