# Generated by Django 3.0.7 on 2020-06-17 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investors', '0058_auto_20200614_0850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tradestrategy',
            name='applied_period',
            field=models.CharField(blank=True, choices=[('15', '15分钟'), ('W', '周线'), ('M', '月线'), ('60', '60分钟'), ('30', '30分钟'), ('D', '日线')], default='60', max_length=2, null=True, verbose_name='应用周期'),
        ),
        migrations.AlterField(
            model_name='tradestrategy',
            name='category',
            field=models.CharField(blank=True, choices=[('S', '卖'), ('B', '买'), ('H', '持仓')], max_length=50, null=True, verbose_name='策略分类'),
        ),
    ]
