# Generated by Django 3.0.7 on 2020-06-21 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investors', '0063_auto_20200621_1612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tradestrategy',
            name='applied_period',
            field=models.CharField(blank=True, choices=[('30', '30分钟'), ('M', '月线'), ('60', '60分钟'), ('15', '15分钟'), ('W', '周线'), ('D', '日线')], default='60', max_length=2, null=True, verbose_name='应用周期'),
        ),
    ]
