# Generated by Django 3.0.7 on 2020-07-09 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investors', '0071_auto_20200628_1551'),
    ]

    operations = [
        migrations.AddField(
            model_name='strategyanalysiscode',
            name='category',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='策略分类'),
        ),
        migrations.AlterField(
            model_name='tradestrategy',
            name='applied_period',
            field=models.CharField(blank=True, choices=[('D', '日线'), ('M', '月线'), ('60', '60分钟'), ('W', '周线'), ('15', '15分钟'), ('30', '30分钟')], default='60', max_length=2, null=True, verbose_name='应用周期'),
        ),
        migrations.AlterField(
            model_name='tradestrategy',
            name='category',
            field=models.CharField(blank=True, choices=[('B', '买'), ('S', '卖'), ('H', '持仓')], max_length=50, null=True, verbose_name='策略分类'),
        ),
    ]
