# Generated by Django 3.0.7 on 2020-09-10 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investors', '0076_auto_20200910_2144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tradestrategy',
            name='applied_period',
            field=models.CharField(blank=True, choices=[('W', '周线'), ('M', '月线'), ('D', '日线'), ('60', '60分钟'), ('30', '30分钟'), ('15', '15分钟')], default='60', max_length=2, null=True, verbose_name='应用周期'),
        ),
        migrations.AlterField(
            model_name='tradestrategy',
            name='category',
            field=models.CharField(blank=True, choices=[('B', '买'), ('H', '持仓'), ('S', '卖')], max_length=50, null=True, verbose_name='策略分类'),
        ),
    ]
