# Generated by Django 3.0.7 on 2020-09-10 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investors', '0077_auto_20200910_2158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tradestrategy',
            name='applied_period',
            field=models.CharField(blank=True, choices=[('M', '月线'), ('60', '60分钟'), ('30', '30分钟'), ('W', '周线'), ('D', '日线'), ('15', '15分钟')], default='60', max_length=2, null=True, verbose_name='应用周期'),
        ),
        migrations.AlterField(
            model_name='tradestrategy',
            name='category',
            field=models.CharField(blank=True, choices=[('H', '持仓'), ('S', '卖'), ('B', '买')], max_length=50, null=True, verbose_name='策略分类'),
        ),
    ]
