# Generated by Django 3.0.7 on 2020-09-11 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investors', '0079_auto_20200911_0830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tradestrategy',
            name='applied_period',
            field=models.CharField(blank=True, choices=[('15', '15分钟'), ('M', '月线'), ('30', '30分钟'), ('W', '周线'), ('60', '60分钟'), ('D', '日线')], default='60', max_length=2, null=True, verbose_name='应用周期'),
        ),
        migrations.AlterField(
            model_name='tradestrategy',
            name='category',
            field=models.CharField(blank=True, choices=[('S', '卖'), ('H', '持仓'), ('B', '买')], max_length=50, null=True, verbose_name='策略分类'),
        ),
    ]
