# Generated by Django 3.0.7 on 2020-09-12 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investors', '0081_auto_20200911_1327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tradestrategy',
            name='applied_period',
            field=models.CharField(blank=True, choices=[('D', '日线'), ('M', '月线'), ('W', '周线'), ('15', '15分钟'), ('60', '60分钟'), ('30', '30分钟')], default='60', max_length=2, null=True, verbose_name='应用周期'),
        ),
        migrations.AlterField(
            model_name='tradestrategy',
            name='category',
            field=models.CharField(blank=True, choices=[('H', '持仓'), ('B', '买'), ('S', '卖')], max_length=50, null=True, verbose_name='策略分类'),
        ),
    ]
