# Generated by Django 3.0.7 on 2020-10-01 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investors', '0082_auto_20200912_2155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tradestrategy',
            name='applied_period',
            field=models.CharField(blank=True, choices=[('W', '周线'), ('D', '日线'), ('15', '15分钟'), ('30', '30分钟'), ('60', '60分钟'), ('M', '月线')], default='60', max_length=2, null=True, verbose_name='应用周期'),
        ),
    ]
