# Generated by Django 3.0.2 on 2021-08-22 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investors', '0084_auto_20210822_1456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockfollowing',
            name='ts_code',
            field=models.CharField(blank=True, max_length=50, verbose_name='TS代码'),
        ),
        migrations.AlterField(
            model_name='tradestrategy',
            name='applied_period',
            field=models.CharField(blank=True, choices=[('15', '15分钟'), ('W', '周线'), ('D', '日线'), ('30', '30分钟'), ('60', '60分钟'), ('M', '月线')], default='60', max_length=2, null=True, verbose_name='应用周期'),
        ),
        migrations.AlterField(
            model_name='tradestrategy',
            name='category',
            field=models.CharField(blank=True, choices=[('H', '持仓'), ('B', '买'), ('S', '卖')], max_length=50, null=True, verbose_name='策略分类'),
        ),
    ]
