# Generated by Django 3.0.2 on 2020-04-20 13:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TradeAccount',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('last_mod_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='最后更新时间')),
                ('account_provider', models.CharField(blank=True, choices=[('htzq', '华泰证券'), ('zszq', '招商证券'), ('gfzq', '广发证券'), ('swhy', '申万宏源'), ('zygj', '中银国际')], max_length=50, null=True, verbose_name='开户证券公司')),
                ('account_type', models.CharField(blank=True, max_length=50, null=True, verbose_name='账户类型')),
                ('account_name', models.CharField(max_length=50, verbose_name='账户名称')),
                ('account_capital', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='本金')),
                ('account_balance', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='账户余额')),
                ('service_charge', models.DecimalField(decimal_places=10, default=0.0005, max_digits=10, verbose_name='交易手续费')),
                ('activate_date', models.DateField(default=django.utils.timezone.now, verbose_name='开户时间')),
                ('is_valid', models.BooleanField(default=True, verbose_name='是否有效')),
                ('is_default', models.BooleanField(default=False, verbose_name='默认账户')),
                ('trader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='持仓人')),
            ],
            options={
                'verbose_name': '股票账户',
                'verbose_name_plural': '股票账户',
                'ordering': ['-last_mod_time'],
                'get_latest_by': 'id',
                'unique_together': {('account_name', 'trader')},
            },
        ),
        migrations.CreateModel(
            name='TradeAccountSnapshot',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('last_mod_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='最后更新时间')),
                ('account_capital', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='本金')),
                ('profit', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='利润')),
                ('profit_change', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='利润变化')),
                ('profit_ratio', models.DecimalField(decimal_places=5, default=0, max_digits=10, verbose_name='利润率')),
                ('snap_date', models.DateField(default=django.utils.timezone.now, verbose_name='快照时间')),
                ('applied_period', models.CharField(blank=True, choices=[('m', '月'), ('w', '周'), ('d', '日')], default='d', max_length=1, verbose_name='收益周期')),
                ('trade_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tradeaccounts.TradeAccount', verbose_name='股票账户')),
                ('trader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='持仓人')),
            ],
            options={
                'verbose_name': '收益快照',
                'verbose_name_plural': '收益快照',
                'ordering': ['-last_mod_time'],
                'get_latest_by': 'id',
            },
        ),
        migrations.CreateModel(
            name='Positions',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('last_mod_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='最后更新时间')),
                ('market', models.CharField(max_length=10, verbose_name='股票市场')),
                ('stock_name', models.CharField(max_length=50, verbose_name='股票名称')),
                ('stock_code', models.CharField(max_length=50, verbose_name='股票代码')),
                ('position_price', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='持仓价格')),
                ('current_price', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='股票现价')),
                ('profit', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='利润')),
                ('profit_ratio', models.CharField(blank=True, max_length=100, null=True, verbose_name='利润率')),
                ('cash', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='投入现金额')),
                ('lots', models.PositiveIntegerField(default=0, verbose_name='持仓')),
                ('target_position', models.PositiveIntegerField(default=0, verbose_name='目标仓位（股）')),
                ('is_liquidated', models.BooleanField(db_index=True, default=False, verbose_name='是否清仓')),
                ('is_sychronized', models.BooleanField(default=False, verbose_name='是否同步')),
                ('sychronized_datetime', models.DateTimeField(blank=True, null=True, verbose_name='同步时间')),
                ('trade_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tradeaccounts.TradeAccount', verbose_name='交易账户')),
                ('trader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='持仓人')),
            ],
            options={
                'verbose_name': '我的持仓',
                'verbose_name_plural': '我的持仓',
                'ordering': ['stock_code'],
                'get_latest_by': 'id',
            },
        ),
    ]
