# Generated by Django 3.0.2 on 2020-04-28 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tradeaccounts', '0003_auto_20200428_2017'),
    ]

    operations = [
        migrations.AddField(
            model_name='positions',
            name='ftd',
            field=models.DateTimeField(blank=True, null=True, verbose_name='建仓时间'),
        ),
        migrations.AddField(
            model_name='positions',
            name='ltd',
            field=models.DateTimeField(blank=True, null=True, verbose_name='清仓时间'),
        ),
    ]
