# Generated by Django 3.0.7 on 2020-06-26 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tradeaccounts', '0059_auto_20200625_2224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tradeaccountsnapshot',
            name='applied_period',
            field=models.CharField(blank=True, choices=[('m', '月'), ('w', '周'), ('d', '日')], default='d', max_length=1, verbose_name='收益周期'),
        ),
    ]
