# Generated by Django 3.0.7 on 2020-10-24 00:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tradeaccounts', '0072_auto_20201001_1951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockpositionsnapshot',
            name='applied_period',
            field=models.CharField(blank=True, choices=[('d', '日'), ('m', '月'), ('w', '周')], default='d', max_length=1, verbose_name='收益周期'),
        ),
        migrations.AlterField(
            model_name='tradeaccountsnapshot',
            name='applied_period',
            field=models.CharField(blank=True, choices=[('d', '日'), ('m', '月'), ('w', '周')], default='d', max_length=1, verbose_name='收益周期'),
        ),
        migrations.CreateModel(
            name='PositionComments',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('last_mod_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='最后更新时间')),
                ('stock_name', models.CharField(max_length=50, verbose_name='股票名称')),
                ('stock_code', models.CharField(max_length=50, verbose_name='股票代码')),
                ('pct_chg', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='当前涨幅')),
                ('position_pct_chg', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='持仓涨幅')),
                ('position_period', models.DecimalField(decimal_places=5, default=0, max_digits=10, verbose_name='持仓周期')),
                ('comments', models.CharField(max_length=5000, verbose_name='评论内容')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='tradeaccounts.Positions', verbose_name='持仓编号')),
                ('trader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='持仓人')),
            ],
            options={
                'verbose_name': '持仓评论',
                'verbose_name_plural': '持仓评论',
                'ordering': ['-created_time'],
                'get_latest_by': 'id',
            },
        ),
    ]
