# Generated by Django 3.0.7 on 2020-10-24 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tradeaccounts', '0073_auto_20201024_0808'),
    ]

    operations = [
        migrations.AddField(
            model_name='positioncomments',
            name='current_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='当前价格'),
        ),
        migrations.AlterField(
            model_name='stockpositionsnapshot',
            name='applied_period',
            field=models.CharField(blank=True, choices=[('w', '周'), ('m', '月'), ('d', '日')], default='d', max_length=1, verbose_name='收益周期'),
        ),
        migrations.AlterField(
            model_name='tradeaccountsnapshot',
            name='applied_period',
            field=models.CharField(blank=True, choices=[('w', '周'), ('m', '月'), ('d', '日')], default='d', max_length=1, verbose_name='收益周期'),
        ),
    ]
