# Generated by Django 3.0.7 on 2020-10-24 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tradeaccounts', '0074_auto_20201024_1441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='positioncomments',
            name='current_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='当前价格'),
        ),
        migrations.AlterField(
            model_name='positioncomments',
            name='pct_chg',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='当前涨幅'),
        ),
        migrations.AlterField(
            model_name='positioncomments',
            name='position_pct_chg',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='持仓涨幅'),
        ),
        migrations.AlterField(
            model_name='positioncomments',
            name='position_period',
            field=models.DecimalField(decimal_places=0, max_digits=10, verbose_name='持仓周期'),
        ),
        migrations.AlterField(
            model_name='stockpositionsnapshot',
            name='applied_period',
            field=models.CharField(blank=True, choices=[('d', '日'), ('w', '周'), ('m', '月')], default='d', max_length=1, verbose_name='收益周期'),
        ),
        migrations.AlterField(
            model_name='tradeaccountsnapshot',
            name='applied_period',
            field=models.CharField(blank=True, choices=[('d', '日'), ('w', '周'), ('m', '月')], default='d', max_length=1, verbose_name='收益周期'),
        ),
    ]
