# Generated by Django 3.0.7 on 2020-10-24 11:37

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tradeaccounts', '0075_auto_20201024_1524'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='positioncomments',
            options={'ordering': ['created_time'], 'verbose_name': '持仓评论', 'verbose_name_plural': '持仓评论'},
        ),
        migrations.AlterUniqueTogether(
            name='positioncomments',
            unique_together={('stock_code', 'trader', 'position', 'comments')},
        ),
    ]
