# Generated by Django 3.0.2 on 2020-01-22 11:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Positions',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('last_mod_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='修改时间')),
                ('market', models.CharField(max_length=10, verbose_name='股票市场')),
                ('stock_name', models.CharField(max_length=50, verbose_name='股票名称')),
                ('stock_code', models.CharField(max_length=50, verbose_name='股票代码')),
                ('position_price', models.FloatField(verbose_name='持仓价格')),
                ('current_price', models.FloatField(verbose_name='股票现价')),
                ('profit', models.FloatField(default=0.0, verbose_name='利润')),
                ('cash', models.FloatField(default=0.0, verbose_name='投入现金额')),
                ('lots', models.PositiveIntegerField(default=0, verbose_name='持仓量(手)')),
                ('position', models.CharField(max_length=50, verbose_name='仓位')),
                ('is_liquadated', models.BooleanField(db_index=True, default=False, verbose_name='是否清仓')),
            ],
            options={
                'verbose_name': '持仓',
                'verbose_name_plural': '持仓',
                'ordering': ['stock_code'],
                'get_latest_by': 'id',
            },
        ),
        migrations.CreateModel(
            name='TradeRec',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('last_mod_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='修改时间')),
                ('market', models.CharField(editable=False, max_length=10, verbose_name='股票市场')),
                ('stock_name', models.CharField(max_length=50, verbose_name='股票名称')),
                ('stock_code', models.CharField(max_length=50, verbose_name='股票代码')),
                ('direction', models.CharField(choices=[('b', '买入'), ('s', '卖出')], default='b', max_length=1, verbose_name='交易类型')),
                ('trade_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='交易时间')),
                ('price', models.FloatField(verbose_name='交易价格')),
                ('lots', models.PositiveIntegerField(default=100, verbose_name='交易量(手)')),
                ('cash', models.FloatField(blank=True, null=True, verbose_name='投入现金额')),
                ('position', models.CharField(max_length=50, verbose_name='交易仓位')),
                ('visible', models.CharField(choices=[('g', '公开'), ('s', '私密'), ('f', '仅好友')], default='s', max_length=1, verbose_name='可见性')),
                ('comment_status', models.CharField(choices=[('o', '打开'), ('c', '关闭')], default='c', max_length=1, verbose_name='评论状态')),
                ('views', models.PositiveIntegerField(default=0, verbose_name='浏览量')),
                ('featured_image', models.ImageField(blank=True, null=True, upload_to='investmgr_pictures/%Y/%m/%d/', verbose_name='特色图片')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否被删除')),
            ],
            options={
                'verbose_name': '交易记录',
                'verbose_name_plural': '交易记录',
                'ordering': ['-created_time'],
                'get_latest_by': 'id',
            },
        ),
        migrations.CreateModel(
            name='TradeStrategy',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('last_mod_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='修改时间')),
                ('name', models.CharField(max_length=30, unique=True, verbose_name='策略名')),
            ],
            options={
                'verbose_name': '交易策略',
                'verbose_name_plural': '交易策略',
                'ordering': ['name'],
            },
        ),
    ]
