# Generated by Django 3.0.2 on 2020-01-22 11:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('investmgr', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradestrategy',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='创建者'),
        ),
        migrations.AddField(
            model_name='tradestrategy',
            name='parent_strategy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='investmgr.TradeStrategy', verbose_name='父级策略'),
        ),
        migrations.AddField(
            model_name='traderec',
            name='in_stock_positions',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='investmgr.Positions', verbose_name='股票持仓'),
        ),
        migrations.AddField(
            model_name='traderec',
            name='strategy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='investmgr.TradeStrategy', verbose_name='策略'),
        ),
        migrations.AddField(
            model_name='traderec',
            name='trader',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='创建者'),
        ),
        migrations.AddField(
            model_name='positions',
            name='trader',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='持仓人'),
        ),
    ]
