# Generated by Django 3.0.2 on 2020-01-22 12:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('investmgr', '0002_auto_20200122_1940'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockNameCodeMap',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('last_mod_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='修改时间')),
                ('market', models.CharField(blank=True, max_length=50, null=True, verbose_name='股票市场')),
                ('stock_name', models.CharField(max_length=50, unique=True, verbose_name='股票名称')),
                ('stock_code', models.CharField(max_length=50, unique=True, verbose_name='股票代码')),
                ('is_valid', models.BooleanField(default=False, verbose_name='是否退市')),
            ],
            options={
                'verbose_name': '股票代码表',
                'verbose_name_plural': '股票代码表',
                'ordering': ['-last_mod_time'],
                'get_latest_by': 'id',
            },
        ),
    ]
