# Generated by Django 3.0.2 on 2020-01-22 13:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('investmgr', '0003_stocknamecodemap'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stocknamecodemap',
            name='market',
            field=models.CharField(blank=True, choices=[('SH', '上海'), ('SZ', '深圳')], max_length=50, null=True, verbose_name='股票市场'),
        ),
        migrations.AlterField(
            model_name='traderec',
            name='featured_image',
            field=models.ImageField(blank=True, editable=False, null=True, upload_to='investmgr_pictures/%Y/%m/%d/', verbose_name='特色图片'),
        ),
        migrations.AlterField(
            model_name='traderec',
            name='in_stock_positions',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='investmgr.Positions', verbose_name='股票持仓'),
        ),
    ]
