# Generated by Django 3.0.2 on 2020-01-23 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investmgr', '0004_auto_20200122_2114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='positions',
            name='current_price',
            field=models.FloatField(default=0, verbose_name='股票现价'),
        ),
        migrations.AlterField(
            model_name='positions',
            name='position',
            field=models.CharField(default='0', max_length=50, verbose_name='仓位'),
        ),
        migrations.AlterField(
            model_name='positions',
            name='position_price',
            field=models.FloatField(default=0, verbose_name='持仓价格'),
        ),
    ]
