# Generated by Django 3.0.2 on 2020-01-23 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investmgr', '0005_auto_20200123_1727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='positions',
            name='position',
            field=models.FloatField(default='0', verbose_name='仓位'),
        ),
        migrations.AlterField(
            model_name='traderec',
            name='position',
            field=models.FloatField(verbose_name='交易仓位'),
        ),
    ]
