# Generated by Django 3.0.2 on 2020-01-24 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investmgr', '0006_auto_20200123_2106'),
    ]

    operations = [
        migrations.RenameField(
            model_name='positions',
            old_name='position',
            new_name='target_position',
        ),
        migrations.RemoveField(
            model_name='traderec',
            name='lots',
        ),
        migrations.RemoveField(
            model_name='traderec',
            name='position',
        ),
        migrations.AddField(
            model_name='traderec',
            name='board_lots',
            field=models.PositiveIntegerField(default=100, verbose_name='本次交易量(手)'),
        ),
        migrations.AddField(
            model_name='traderec',
            name='target_position',
            field=models.PositiveIntegerField(default=100, verbose_name='目标仓位（手）'),
        ),
    ]
