# Generated by Django 3.0.2 on 2020-01-25 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investmgr', '0007_auto_20200124_2113'),
    ]

    operations = [
        migrations.AddField(
            model_name='traderec',
            name='current_price',
            field=models.FloatField(default=0, verbose_name='股票现价'),
        ),
        migrations.AlterField(
            model_name='positions',
            name='lots',
            field=models.PositiveIntegerField(default=0, verbose_name='持仓量(股)'),
        ),
        migrations.AlterField(
            model_name='positions',
            name='target_position',
            field=models.PositiveIntegerField(default=0, verbose_name='目标仓位（股）'),
        ),
        migrations.AlterField(
            model_name='traderec',
            name='board_lots',
            field=models.PositiveIntegerField(default=100, verbose_name='本次交易量(股)'),
        ),
        migrations.AlterField(
            model_name='traderec',
            name='cash',
            field=models.FloatField(blank=True, null=True, verbose_name='交易现金额'),
        ),
        migrations.AlterField(
            model_name='traderec',
            name='target_position',
            field=models.PositiveIntegerField(default=100, verbose_name='目标仓位（股）'),
        ),
    ]
