# Generated by Django 3.0.2 on 2020-01-25 13:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('investmgr', '0008_auto_20200125_1405'),
    ]

    operations = [
        migrations.RenameField(
            model_name='traderec',
            old_name='is_deleted',
            new_name='is_liquadated',
        ),
        migrations.AlterField(
            model_name='positions',
            name='last_mod_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='最后更新时间'),
        ),
        migrations.AlterField(
            model_name='stocknamecodemap',
            name='last_mod_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='最后更新时间'),
        ),
        migrations.AlterField(
            model_name='traderec',
            name='last_mod_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='最后更新时间'),
        ),
        migrations.AlterField(
            model_name='tradestrategy',
            name='last_mod_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='最后更新时间'),
        ),
    ]
