# Generated by Django 3.0.2 on 2020-01-26 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investmgr', '0009_auto_20200125_2106'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradestrategy',
            name='applied_period',
            field=models.CharField(blank=True, choices=[('mm', '月线'), ('30', '30分钟'), ('dd', '日线'), ('15', '15分钟'), ('wk', '周线'), ('60', '60分钟')], default='60', max_length=2, verbose_name='应用周期'),
        ),
        migrations.AlterField(
            model_name='traderec',
            name='is_liquadated',
            field=models.BooleanField(default=False, editable=False, verbose_name='是否已清仓'),
        ),
    ]
