# Generated by Django 3.0.2 on 2020-01-26 07:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('investmgr', '0010_auto_20200126_1142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tradestrategy',
            name='applied_period',
            field=models.CharField(blank=True, choices=[('wk', '周线'), ('30', '30分钟'), ('mm', '月线'), ('60', '60分钟'), ('dd', '日线'), ('15', '15分钟')], default='60', max_length=2, verbose_name='应用周期'),
        ),
        migrations.CreateModel(
            name='TradeSettings',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('last_mod_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='最后更新时间')),
                ('name', models.CharField(max_length=50, verbose_name='参数名')),
                ('value', models.CharField(max_length=50, verbose_name='参数值')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
            ],
            options={
                'verbose_name': '交易参数设置',
                'verbose_name_plural': '交易参数设置',
                'ordering': ['name'],
            },
        ),
    ]
