# Generated by Django 3.0.2 on 2020-01-26 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investmgr', '0011_auto_20200126_1545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tradesettings',
            name='name',
            field=models.CharField(choices=[('TARGET_POSITION', 'target_position')], max_length=50, verbose_name='参数名'),
        ),
        migrations.AlterField(
            model_name='tradestrategy',
            name='applied_period',
            field=models.CharField(blank=True, choices=[('60', '60分钟'), ('wk', '周线'), ('15', '15分钟'), ('mm', '月线'), ('dd', '日线'), ('30', '30分钟')], default='60', max_length=2, verbose_name='应用周期'),
        ),
    ]
