# Generated by Django 3.0.2 on 2020-01-29 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investmgr', '0012_auto_20200126_1548'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='traderec',
            options={'get_latest_by': 'id', 'ordering': ['-last_mod_time'], 'verbose_name': '交易记录', 'verbose_name_plural': '交易记录'},
        ),
        migrations.AlterField(
            model_name='positions',
            name='cash',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='投入现金额'),
        ),
        migrations.AlterField(
            model_name='positions',
            name='current_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='股票现价'),
        ),
        migrations.AlterField(
            model_name='positions',
            name='position_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='持仓价格'),
        ),
        migrations.AlterField(
            model_name='positions',
            name='profit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='利润'),
        ),
        migrations.AlterField(
            model_name='traderec',
            name='cash',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='交易现金额'),
        ),
        migrations.AlterField(
            model_name='traderec',
            name='current_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='股票现价'),
        ),
        migrations.AlterField(
            model_name='traderec',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='交易价格'),
        ),
        migrations.AlterField(
            model_name='tradesettings',
            name='name',
            field=models.CharField(choices=[('TARGET_POSITION', '目标仓位')], max_length=50, verbose_name='参数名'),
        ),
        migrations.AlterField(
            model_name='tradestrategy',
            name='applied_period',
            field=models.CharField(blank=True, choices=[('30', '30分钟'), ('wk', '周线'), ('mm', '月线'), ('60', '60分钟'), ('dd', '日线'), ('15', '15分钟')], default='60', max_length=2, verbose_name='应用周期'),
        ),
    ]
