# Generated by Django 3.0.2 on 2020-01-30 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investmgr', '0013_auto_20200129_2136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='traderec',
            name='target_position',
            field=models.PositiveIntegerField(blank=True, default=100, null=True, verbose_name='目标仓位（股）'),
        ),
        migrations.AlterField(
            model_name='tradestrategy',
            name='applied_period',
            field=models.CharField(blank=True, choices=[('mm', '月线'), ('wk', '周线'), ('dd', '日线'), ('15', '15分钟'), ('60', '60分钟'), ('30', '30分钟')], default='60', max_length=2, verbose_name='应用周期'),
        ),
    ]
