# Generated by Django 3.0.2 on 2020-02-03 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investmgr', '0016_auto_20200203_2017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tradestrategy',
            name='applied_period',
            field=models.CharField(blank=True, choices=[('wk', '周线'), ('15', '15分钟'), ('30', '30分钟'), ('mm', '月线'), ('dd', '日线'), ('60', '60分钟')], default='60', max_length=2, verbose_name='应用周期'),
        ),
    ]
