# Generated by Django 3.0.2 on 2020-02-04 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investmgr', '0018_auto_20200204_1538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stocknamecodemap',
            name='en_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='英文全称'),
        ),
        migrations.AlterField(
            model_name='stocknamecodemap',
            name='fullname',
            field=models.CharField(blank=True, max_length=100, verbose_name='股票全称'),
        ),
        migrations.AlterField(
            model_name='tradestrategy',
            name='applied_period',
            field=models.CharField(blank=True, choices=[('15', '15分钟'), ('dd', '日线'), ('mm', '月线'), ('30', '30分钟'), ('60', '60分钟'), ('wk', '周线')], default='60', max_length=2, verbose_name='应用周期'),
        ),
    ]
