# Generated by Django 3.0.2 on 2020-02-04 08:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('investmgr', '0019_auto_20200204_1553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stocknamecodemap',
            name='area',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='所在地域'),
        ),
        migrations.AlterField(
            model_name='stocknamecodemap',
            name='en_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='英文全称'),
        ),
        migrations.AlterField(
            model_name='stocknamecodemap',
            name='exchange',
            field=models.CharField(blank=True, choices=[('SSE', '上交所'), ('SZSE', '深交所')], max_length=10, null=True, verbose_name='交易所代码'),
        ),
        migrations.AlterField(
            model_name='stocknamecodemap',
            name='fullname',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='股票全称'),
        ),
        migrations.AlterField(
            model_name='stocknamecodemap',
            name='industry',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='所属行业'),
        ),
        migrations.AlterField(
            model_name='stocknamecodemap',
            name='is_hs',
            field=models.CharField(blank=True, choices=[('N', '否'), ('H', '沪股通'), ('S', '深股通')], max_length=10, null=True, verbose_name='是否沪深港通标的'),
        ),
        migrations.AlterField(
            model_name='stocknamecodemap',
            name='list_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='上市日期'),
        ),
        migrations.AlterField(
            model_name='stocknamecodemap',
            name='list_status',
            field=models.CharField(blank=True, choices=[('L', '上市'), ('D', '退市'), ('P', '暂停上市')], max_length=1, null=True, verbose_name='上市状态'),
        ),
        migrations.AlterField(
            model_name='tradestrategy',
            name='applied_period',
            field=models.CharField(blank=True, choices=[('wk', '周线'), ('60', '60分钟'), ('15', '15分钟'), ('mm', '月线'), ('dd', '日线'), ('30', '30分钟')], default='60', max_length=2, verbose_name='应用周期'),
        ),
    ]
