# Generated by Django 3.0.2 on 2020-02-06 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investmgr', '0020_auto_20200204_1618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='traderec',
            name='market',
            field=models.CharField(choices=[('ZB', '主板'), ('ZXB', '中小板'), ('CYB', '创业板'), ('KCB', '科创板')], editable=False, max_length=10, verbose_name='股票市场'),
        ),
        migrations.AlterField(
            model_name='tradesettings',
            name='name',
            field=models.CharField(choices=[('TARGET_POSITION', '目标仓位'), ('SERVICE_FEE', '交易手续费'), ('STAMP_TAX', '印花税')], max_length=50, verbose_name='参数名'),
        ),
        migrations.AlterField(
            model_name='tradestrategy',
            name='applied_period',
            field=models.CharField(blank=True, choices=[('60', '60分钟'), ('15', '15分钟'), ('wk', '周线'), ('30', '30分钟'), ('mm', '月线'), ('dd', '日线')], default='60', max_length=2, verbose_name='应用周期'),
        ),
    ]
