# Generated by Django 3.0.2 on 2020-02-13 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investmgr', '0023_auto_20200213_1116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tradestrategy',
            name='applied_period',
            field=models.CharField(blank=True, choices=[('mm', '月线'), ('wk', '周线'), ('15', '15分钟'), ('dd', '日线'), ('60', '60分钟'), ('30', '30分钟')], default='60', max_length=2, verbose_name='应用周期'),
        ),
    ]
