# Generated by Django 3.0.2 on 2020-02-15 13:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('investmgr', '0025_auto_20200213_1738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tradestrategy',
            name='applied_period',
            field=models.CharField(blank=True, choices=[('wk', '周线'), ('15', '15分钟'), ('mm', '月线'), ('60', '60分钟'), ('dd', '日线'), ('30', '30分钟')], default='60', max_length=2, verbose_name='应用周期'),
        ),
        migrations.CreateModel(
            name='TradeAccount',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('last_mod_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='最后更新时间')),
                ('account_name', models.CharField(max_length=50, verbose_name='账户名称')),
                ('account_balance', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='账户余额')),
                ('account_provider', models.CharField(blank=True, choices=[('htzq', '华泰证券'), ('zszq', '招商证券'), ('gfzq', '广发证券'), ('swhy', '申万宏源')], max_length=50, null=True, verbose_name='开户证券公司')),
                ('trade_fee', models.FloatField(default=0.0005, verbose_name='交易手续费')),
                ('activate_date', models.DateField(default=django.utils.timezone.now, verbose_name='开户时间')),
                ('is_valid', models.BooleanField(default=True, verbose_name='是否有效')),
                ('trader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='持仓人')),
            ],
            options={
                'verbose_name': '股票账户',
                'verbose_name_plural': '股票账户',
                'ordering': ['-last_mod_time'],
                'get_latest_by': 'id',
            },
        ),
        migrations.AddField(
            model_name='positions',
            name='trade_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='investmgr.TradeAccount', verbose_name='交易账户'),
        ),
        migrations.AddField(
            model_name='traderec',
            name='trade_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='investmgr.TradeAccount', verbose_name='交易账户'),
        ),
    ]
