# Generated by Django 3.0.2 on 2020-02-16 13:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('investmgr', '0026_auto_20200215_2116'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tradeaccount',
            name='account_balance',
        ),
        migrations.AddField(
            model_name='tradeaccount',
            name='account_capital',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='本金余额'),
        ),
        migrations.AlterField(
            model_name='tradeaccount',
            name='account_provider',
            field=models.CharField(blank=True, choices=[('htzq', '华泰证券'), ('zszq', '招商证券'), ('gfzq', '广发证券'), ('swhy', '申万宏源'), ('zygj', '中银国际')], max_length=50, null=True, verbose_name='开户证券公司'),
        ),
        migrations.AlterField(
            model_name='tradestrategy',
            name='applied_period',
            field=models.CharField(blank=True, choices=[('dd', '日线'), ('15', '15分钟'), ('wk', '周线'), ('60', '60分钟'), ('30', '30分钟'), ('mm', '月线')], default='60', max_length=2, verbose_name='应用周期'),
        ),
        migrations.CreateModel(
            name='TradeProfitSnapshot',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('last_mod_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='最后更新时间')),
                ('profit', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='利润')),
                ('profit_change', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='利润变化')),
                ('profit_ratio', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='利润率')),
                ('snap_date', models.DateField(default=django.utils.timezone.now, verbose_name='快照时间')),
                ('applied_period', models.CharField(blank=True, choices=[('w', '周'), ('d', '日'), ('m', '月')], default='d', max_length=1, verbose_name='收益周期')),
                ('account_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='investmgr.TradeAccount', verbose_name='股票账户')),
                ('trader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='持仓人')),
            ],
            options={
                'verbose_name': '收益快照',
                'verbose_name_plural': '收益快照',
                'ordering': ['-last_mod_time'],
                'get_latest_by': 'id',
            },
        ),
    ]
