# Generated by Django 3.0.2 on 2020-02-17 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investmgr', '0027_auto_20200216_2125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tradeprofitsnapshot',
            name='profit_ratio',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=10, verbose_name='利润率'),
        ),
        migrations.AlterField(
            model_name='tradestrategy',
            name='applied_period',
            field=models.CharField(blank=True, choices=[('mm', '月线'), ('dd', '日线'), ('wk', '周线'), ('15', '15分钟'), ('30', '30分钟'), ('60', '60分钟')], default='60', max_length=2, verbose_name='应用周期'),
        ),
    ]
