# Generated by Django 3.0.2 on 2020-02-17 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investmgr', '0028_auto_20200217_0900'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradeaccount',
            name='account_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='账户余额'),
        ),
        migrations.AlterField(
            model_name='tradeaccount',
            name='account_capital',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='本金'),
        ),
        migrations.AlterField(
            model_name='tradeprofitsnapshot',
            name='applied_period',
            field=models.CharField(blank=True, choices=[('d', '日'), ('m', '月'), ('w', '周')], default='d', max_length=1, verbose_name='收益周期'),
        ),
        migrations.AlterField(
            model_name='tradestrategy',
            name='applied_period',
            field=models.CharField(blank=True, choices=[('mm', '月线'), ('30', '30分钟'), ('wk', '周线'), ('60', '60分钟'), ('dd', '日线'), ('15', '15分钟')], default='60', max_length=2, verbose_name='应用周期'),
        ),
    ]
