# Generated by Django 3.0.2 on 2020-02-18 14:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('investmgr', '0029_auto_20200217_2134'),
    ]

    operations = [
        migrations.AddField(
            model_name='traderec',
            name='sell_stock_refer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='investmgr.TradeRec', verbose_name='对应买入交易'),
        ),
        migrations.AlterField(
            model_name='tradeprofitsnapshot',
            name='applied_period',
            field=models.CharField(blank=True, choices=[('w', '周'), ('d', '日'), ('m', '月')], default='d', max_length=1, verbose_name='收益周期'),
        ),
        migrations.AlterField(
            model_name='tradestrategy',
            name='applied_period',
            field=models.CharField(blank=True, choices=[('30', '30分钟'), ('dd', '日线'), ('60', '60分钟'), ('mm', '月线'), ('15', '15分钟'), ('wk', '周线')], default='60', max_length=2, verbose_name='应用周期'),
        ),
        migrations.CreateModel(
            name='StockPositionTransaction',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('last_mod_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='最后更新时间')),
                ('stock_name', models.CharField(max_length=50, verbose_name='股票名称')),
                ('stock_code', models.CharField(max_length=50, verbose_name='股票代码')),
                ('transaction_type', models.CharField(choices=[('b', '买入'), ('s', '卖出'), ('a', '调整')], default='b', max_length=1, verbose_name='交易类型')),
                ('trade_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='交易时间')),
                ('price', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='交易价格')),
                ('current_price', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='股票现价')),
                ('from_lot', models.PositiveIntegerField(default=100, verbose_name='初始持仓（股）')),
                ('to_lot', models.PositiveIntegerField(default=100, verbose_name='交易后持仓（股）')),
                ('created_by', models.CharField(default='system', editable=False, max_length=50, verbose_name='创建人')),
                ('account_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='investmgr.TradeAccount', verbose_name='股票账户')),
                ('stock_positions', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='investmgr.Positions', verbose_name='股票持仓')),
                ('trader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='持仓人')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
