# Generated by Django 3.0.2 on 2020-02-20 13:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('investmgr', '0030_auto_20200218_2208'),
    ]

    operations = [
        migrations.AddField(
            model_name='traderec',
            name='created_or_mod_by',
            field=models.CharField(default='human', editable=False, max_length=50, verbose_name='创建人'),
        ),
        migrations.AddField(
            model_name='traderec',
            name='is_sold',
            field=models.BooleanField(default=False, verbose_name='是否已卖出'),
        ),
        migrations.AddField(
            model_name='traderec',
            name='sold_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='卖出时间'),
        ),
        migrations.AlterField(
            model_name='tradestrategy',
            name='applied_period',
            field=models.CharField(blank=True, choices=[('mm', '月线'), ('dd', '日线'), ('15', '15分钟'), ('60', '60分钟'), ('wk', '周线'), ('30', '30分钟')], default='60', max_length=2, verbose_name='应用周期'),
        ),
    ]
