# Generated by Django 3.0.2 on 2020-02-21 14:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('investmgr', '0032_auto_20200220_2203'),
    ]

    operations = [
        migrations.AddField(
            model_name='traderec',
            name='lots_remain',
            field=models.PositiveIntegerField(default=0, verbose_name='剩余持仓'),
        ),
        migrations.AddField(
            model_name='traderec',
            name='parent_rec',
            field=models.CharField(blank=True, default='05LBFG', max_length=10, null=True, verbose_name='买入记录编号'),
        ),
        migrations.AddField(
            model_name='traderec',
            name='sell_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='卖出价'),
        ),
        migrations.AlterField(
            model_name='tradeprofitsnapshot',
            name='applied_period',
            field=models.CharField(blank=True, choices=[('d', '日'), ('m', '月'), ('w', '周')], default='d', max_length=1, verbose_name='收益周期'),
        ),
        migrations.AlterField(
            model_name='traderec',
            name='sell_stock_refer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='investmgr.TradeRec', verbose_name='卖对应之买入'),
        ),
        migrations.AlterField(
            model_name='tradestrategy',
            name='applied_period',
            field=models.CharField(blank=True, choices=[('mm', '月线'), ('30', '30分钟'), ('15', '15分钟'), ('wk', '周线'), ('dd', '日线'), ('60', '60分钟')], default='60', max_length=2, verbose_name='应用周期'),
        ),
    ]
