# Generated by Django 3.0.2 on 2020-02-21 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investmgr', '0033_auto_20200221_2217'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='traderec',
            name='parent_rec',
        ),
        migrations.AddField(
            model_name='traderec',
            name='rec_ref_number',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='买入记录编号'),
        ),
        migrations.AlterField(
            model_name='tradeprofitsnapshot',
            name='applied_period',
            field=models.CharField(blank=True, choices=[('m', '月'), ('d', '日'), ('w', '周')], default='d', max_length=1, verbose_name='收益周期'),
        ),
        migrations.AlterField(
            model_name='tradestrategy',
            name='applied_period',
            field=models.CharField(blank=True, choices=[('mm', '月线'), ('60', '60分钟'), ('30', '30分钟'), ('dd', '日线'), ('wk', '周线'), ('15', '15分钟')], default='60', max_length=2, verbose_name='应用周期'),
        ),
    ]
