# Generated by Django 3.0.2 on 2020-02-22 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investmgr', '0034_auto_20200221_2221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tradeprofitsnapshot',
            name='applied_period',
            field=models.CharField(blank=True, choices=[('w', '周'), ('d', '日'), ('m', '月')], default='d', max_length=1, verbose_name='收益周期'),
        ),
        migrations.AlterField(
            model_name='tradestrategy',
            name='applied_period',
            field=models.CharField(blank=True, choices=[('60', '60分钟'), ('wk', '周线'), ('dd', '日线'), ('15', '15分钟'), ('mm', '月线'), ('30', '30分钟')], default='60', max_length=2, verbose_name='应用周期'),
        ),
    ]
