# Generated by Django 3.0.2 on 2020-02-23 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investmgr', '0035_auto_20200222_0840'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='positions',
            options={'get_latest_by': 'id', 'ordering': ['stock_code'], 'verbose_name': '我的持仓', 'verbose_name_plural': '我的持仓'},
        ),
        migrations.AlterField(
            model_name='positions',
            name='lots',
            field=models.PositiveIntegerField(default=0, verbose_name='持仓'),
        ),
        migrations.AlterField(
            model_name='tradeprofitsnapshot',
            name='applied_period',
            field=models.CharField(blank=True, choices=[('m', '月'), ('w', '周'), ('d', '日')], default='d', max_length=1, verbose_name='收益周期'),
        ),
        migrations.AlterField(
            model_name='tradestrategy',
            name='applied_period',
            field=models.CharField(blank=True, choices=[('60', '60分钟'), ('15', '15分钟'), ('dd', '日线'), ('mm', '月线'), ('wk', '周线'), ('30', '30分钟')], default='60', max_length=2, verbose_name='应用周期'),
        ),
    ]
