# Generated by Django 3.0.2 on 2020-02-26 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investmgr', '0036_auto_20200223_0912'),
    ]

    operations = [
        migrations.AlterField(
            model_name='positions',
            name='profit',
            field=models.FloatField(default=0, verbose_name='利润'),
        ),
        migrations.AlterField(
            model_name='tradeprofitsnapshot',
            name='applied_period',
            field=models.CharField(blank=True, choices=[('d', '日'), ('w', '周'), ('m', '月')], default='d', max_length=1, verbose_name='收益周期'),
        ),
        migrations.AlterField(
            model_name='tradestrategy',
            name='applied_period',
            field=models.CharField(blank=True, choices=[('dd', '日线'), ('15', '15分钟'), ('mm', '月线'), ('wk', '周线'), ('60', '60分钟'), ('30', '30分钟')], default='60', max_length=2, verbose_name='应用周期'),
        ),
    ]
