# Generated by Django 3.0.2 on 2020-03-09 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investmgr', '0038_auto_20200229_1500'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradeaccount',
            name='account_type',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='账户类型'),
        ),
        migrations.AlterField(
            model_name='tradeprofitsnapshot',
            name='applied_period',
            field=models.CharField(blank=True, choices=[('w', '周'), ('d', '日'), ('m', '月')], default='d', max_length=1, verbose_name='收益周期'),
        ),
        migrations.AlterField(
            model_name='tradestrategy',
            name='applied_period',
            field=models.CharField(blank=True, choices=[('dd', '日线'), ('15', '15分钟'), ('wk', '周线'), ('60', '60分钟'), ('30', '30分钟'), ('mm', '月线')], default='60', max_length=2, verbose_name='应用周期'),
        ),
    ]
