# Generated by Django 3.0.2 on 2020-03-09 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investmgr', '0039_auto_20200309_2048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tradeaccount',
            name='account_name',
            field=models.CharField(max_length=50, unique=True, verbose_name='账户名称'),
        ),
        migrations.AlterField(
            model_name='tradeprofitsnapshot',
            name='applied_period',
            field=models.CharField(blank=True, choices=[('w', '周'), ('m', '月'), ('d', '日')], default='d', max_length=1, verbose_name='收益周期'),
        ),
        migrations.AlterField(
            model_name='tradestrategy',
            name='applied_period',
            field=models.CharField(blank=True, choices=[('60', '60分钟'), ('wk', '周线'), ('30', '30分钟'), ('dd', '日线'), ('mm', '月线'), ('15', '15分钟')], default='60', max_length=2, verbose_name='应用周期'),
        ),
    ]
