# Generated by Django 3.0.2 on 2020-03-15 00:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('investmgr', '0042_auto_20200314_0750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tradeprofitsnapshot',
            name='applied_period',
            field=models.CharField(blank=True, choices=[('m', '月'), ('w', '周'), ('d', '日')], default='d', max_length=1, verbose_name='收益周期'),
        ),
        migrations.AlterField(
            model_name='tradestrategy',
            name='applied_period',
            field=models.CharField(blank=True, choices=[('15', '15分钟'), ('dd', '日线'), ('mm', '月线'), ('60', '60分钟'), ('30', '30分钟'), ('wk', '周线')], default='60', max_length=2, verbose_name='应用周期'),
        ),
        migrations.CreateModel(
            name='StockPositionSnapshot',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('last_mod_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='最后更新时间')),
                ('stock_name', models.CharField(max_length=50, verbose_name='股票名称')),
                ('stock_code', models.CharField(max_length=50, verbose_name='股票代码')),
                ('profit', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='利润')),
                ('profit_change', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='利润变化')),
                ('profit_ratio', models.DecimalField(decimal_places=5, default=0, max_digits=10, verbose_name='利润率')),
                ('snap_date', models.DateField(default=django.utils.timezone.now, verbose_name='快照时间')),
                ('applied_period', models.CharField(blank=True, choices=[('m', '月'), ('w', '周'), ('d', '日')], default='d', max_length=1, verbose_name='收益周期')),
                ('trade_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='investmgr.TradeAccount', verbose_name='股票账户')),
                ('trader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='持仓人')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
