# Generated by Django 3.0.2 on 2020-03-15 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investmgr', '0043_auto_20200315_0829'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tradeprofitsnapshot',
            old_name='account_name',
            new_name='trade_account',
        ),
        migrations.AlterField(
            model_name='tradestrategy',
            name='applied_period',
            field=models.CharField(blank=True, choices=[('mm', '月线'), ('60', '60分钟'), ('dd', '日线'), ('30', '30分钟'), ('15', '15分钟'), ('wk', '周线')], default='60', max_length=2, verbose_name='应用周期'),
        ),
    ]
