# Generated by Django 3.0.2 on 2020-03-26 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investmgr', '0047_auto_20200323_0900'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradeprofitsnapshot',
            name='account_capital',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='本金'),
        ),
        migrations.AlterField(
            model_name='stockpositionsnapshot',
            name='applied_period',
            field=models.CharField(blank=True, choices=[('w', '周'), ('d', '日'), ('m', '月')], default='d', max_length=1, verbose_name='收益周期'),
        ),
        migrations.AlterField(
            model_name='tradeprofitsnapshot',
            name='applied_period',
            field=models.CharField(blank=True, choices=[('w', '周'), ('d', '日'), ('m', '月')], default='d', max_length=1, verbose_name='收益周期'),
        ),
        migrations.AlterField(
            model_name='tradestrategy',
            name='applied_period',
            field=models.CharField(blank=True, choices=[('dd', '日线'), ('60', '60分钟'), ('mm', '月线'), ('15', '15分钟'), ('wk', '周线'), ('30', '30分钟')], default='60', max_length=2, verbose_name='应用周期'),
        ),
    ]
