# Generated by Django 3.0.2 on 2020-03-28 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investmgr', '0048_auto_20200326_1500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockpositionsnapshot',
            name='applied_period',
            field=models.CharField(blank=True, choices=[('w', '周'), ('m', '月'), ('d', '日')], default='d', max_length=1, verbose_name='收益周期'),
        ),
        migrations.AlterField(
            model_name='tradeprofitsnapshot',
            name='applied_period',
            field=models.CharField(blank=True, choices=[('w', '周'), ('m', '月'), ('d', '日')], default='d', max_length=1, verbose_name='收益周期'),
        ),
        migrations.AlterField(
            model_name='tradestrategy',
            name='applied_period',
            field=models.CharField(blank=True, choices=[('dd', '日线'), ('15', '15分钟'), ('30', '30分钟'), ('60', '60分钟'), ('mm', '月线'), ('wk', '周线')], default='60', max_length=2, verbose_name='应用周期'),
        ),
    ]
