# Generated by Django 3.0.2 on 2020-03-29 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investmgr', '0052_auto_20200328_1931'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradeaccount',
            name='is_default',
            field=models.BooleanField(default=False, verbose_name='默认账户'),
        ),
        migrations.AlterField(
            model_name='stockpositionsnapshot',
            name='applied_period',
            field=models.CharField(blank=True, choices=[('w', '周'), ('d', '日'), ('m', '月')], default='d', max_length=1, verbose_name='收益周期'),
        ),
        migrations.AlterField(
            model_name='tradeprofitsnapshot',
            name='applied_period',
            field=models.CharField(blank=True, choices=[('w', '周'), ('d', '日'), ('m', '月')], default='d', max_length=1, verbose_name='收益周期'),
        ),
        migrations.AlterField(
            model_name='tradestrategy',
            name='applied_period',
            field=models.CharField(blank=True, choices=[('30', '30分钟'), ('mm', '月线'), ('wk', '周线'), ('60', '60分钟'), ('15', '15分钟'), ('dd', '日线')], default='60', max_length=2, verbose_name='应用周期'),
        ),
    ]
