# Generated by Django 3.0.2 on 2020-04-07 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investmgr', '0054_auto_20200330_2135'),
    ]

    operations = [
        migrations.AddField(
            model_name='positions',
            name='is_sychronized',
            field=models.BooleanField(default=False, verbose_name='是否清仓'),
        ),
        migrations.AddField(
            model_name='positions',
            name='sychronized_datetime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='同步时间'),
        ),
        migrations.AlterField(
            model_name='stockpositionsnapshot',
            name='applied_period',
            field=models.CharField(blank=True, choices=[('d', '日'), ('m', '月'), ('w', '周')], default='d', max_length=1, verbose_name='收益周期'),
        ),
        migrations.AlterField(
            model_name='tradeprofitsnapshot',
            name='applied_period',
            field=models.CharField(blank=True, choices=[('d', '日'), ('m', '月'), ('w', '周')], default='d', max_length=1, verbose_name='收益周期'),
        ),
        migrations.AlterField(
            model_name='tradestrategy',
            name='applied_period',
            field=models.CharField(blank=True, choices=[('30', '30分钟'), ('wk', '周线'), ('15', '15分钟'), ('60', '60分钟'), ('mm', '月线'), ('dd', '日线')], default='60', max_length=2, verbose_name='应用周期'),
        ),
    ]
