# Generated by Django 3.0.5 on 2020-04-10 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investmgr', '0055_auto_20200407_2118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='positions',
            name='is_sychronized',
            field=models.BooleanField(default=False, verbose_name='是否同步'),
        ),
        migrations.AlterField(
            model_name='stockpositionsnapshot',
            name='applied_period',
            field=models.CharField(blank=True, choices=[('d', '日'), ('w', '周'), ('m', '月')], default='d', max_length=1, verbose_name='收益周期'),
        ),
        migrations.AlterField(
            model_name='tradeprofitsnapshot',
            name='applied_period',
            field=models.CharField(blank=True, choices=[('d', '日'), ('w', '周'), ('m', '月')], default='d', max_length=1, verbose_name='收益周期'),
        ),
        migrations.AlterField(
            model_name='tradestrategy',
            name='applied_period',
            field=models.CharField(blank=True, choices=[('dd', '日线'), ('30', '30分钟'), ('mm', '月线'), ('60', '60分钟'), ('15', '15分钟'), ('wk', '周线')], default='60', max_length=2, verbose_name='应用周期'),
        ),
    ]
