# Generated by Django 3.0.2 on 2020-04-19 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investmgr', '0056_auto_20200411_1028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockpositionsnapshot',
            name='applied_period',
            field=models.CharField(blank=True, choices=[('d', '日'), ('m', '月'), ('w', '周')], default='d', max_length=1, verbose_name='收益周期'),
        ),
        migrations.AlterField(
            model_name='tradeprofitsnapshot',
            name='applied_period',
            field=models.CharField(blank=True, choices=[('d', '日'), ('m', '月'), ('w', '周')], default='d', max_length=1, verbose_name='收益周期'),
        ),
        migrations.AlterField(
            model_name='tradestrategy',
            name='applied_period',
            field=models.CharField(blank=True, choices=[('60', '60分钟'), ('30', '30分钟'), ('mm', '月线'), ('dd', '日线'), ('15', '15分钟'), ('wk', '周线')], default='60', max_length=2, verbose_name='应用周期'),
        ),
    ]
