# Generated by Django 3.0.2 on 2020-05-07 22:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StockHistoryDaily',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('last_mod_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='最后更新时间')),
                ('ts_code', models.CharField(max_length=15, verbose_name='TS代码')),
                ('trade_date', models.DateField(max_length=6, verbose_name='交易日')),
                ('open', models.FloatField(blank=True, null=True, verbose_name='开盘价')),
                ('high', models.FloatField(blank=True, null=True, verbose_name='最高价')),
                ('pre_close', models.FloatField(blank=True, null=True, verbose_name='前日收盘价')),
                ('close', models.FloatField(blank=True, null=True, verbose_name='收盘价')),
                ('change', models.FloatField(blank=True, null=True, verbose_name='价格变化')),
                ('pct_chg', models.FloatField(blank=True, null=True, verbose_name='价格变化%')),
                ('vol', models.FloatField(blank=True, null=True, verbose_name='交易量')),
                ('amount', models.FloatField(blank=True, null=True, verbose_name='金额')),
                ('chg4', models.FloatField(blank=True, null=True, verbose_name='与4日前变化')),
                ('jiuzhuan_count', models.FloatField(default=-1, verbose_name='九转序列')),
            ],
            options={
                'verbose_name': '股票代码表',
                'verbose_name_plural': '股票代码表',
                'ordering': ['-last_mod_time'],
                'get_latest_by': 'id',
            },
        ),
    ]
