# Generated by Django 3.0.2 on 2020-05-08 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0003_auto_20200508_0705'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stockhistorydaily',
            old_name='jiuzhuan_count',
            new_name='jiuzhuan_count_b',
        ),
    ]
