# Generated by Django 3.0.2 on 2020-05-13 09:33

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('investors', '0012_auto_20200513_1733'),
        ('analysis', '0005_tradestrategystat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tradestrategystat',
            name='applied_period',
            field=models.CharField(blank=True, choices=[('30', '30分钟'), ('dd', '日线'), ('mm', '月线'), ('wk', '周线'), ('60', '60分钟'), ('15', '15分钟')], default='60', max_length=2, verbose_name='应用周期'),
        ),
        migrations.CreateModel(
            name='BStrategyTestResultOnDays',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('last_mod_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='最后更新时间')),
                ('ts_code', models.CharField(db_index=True, max_length=15, verbose_name='TS代码')),
                ('trade_date', models.DateField(verbose_name='交易日')),
                ('test_period', models.IntegerField(blank=True, default=10, verbose_name='测试周期长度')),
                ('open', models.FloatField(blank=True, null=True, verbose_name='开盘价')),
                ('high', models.FloatField(blank=True, null=True, verbose_name='最高价')),
                ('low', models.FloatField(blank=True, null=True, verbose_name='最低价')),
                ('pre_close', models.FloatField(blank=True, null=True, verbose_name='前日收盘价')),
                ('close', models.FloatField(blank=True, null=True, verbose_name='收盘价')),
                ('change', models.FloatField(blank=True, null=True, verbose_name='价格变化')),
                ('pct_chg', models.FloatField(blank=True, null=True, verbose_name='涨幅%')),
                ('vol', models.FloatField(blank=True, null=True, verbose_name='交易量')),
                ('amount', models.FloatField(blank=True, null=True, verbose_name='金额')),
                ('stage_low', models.BooleanField(blank=True, default=False, null=True, verbose_name='低点?')),
                ('stage_low_pct', models.FloatField(blank=True, default=False, null=True, verbose_name='低点/买点%?')),
                ('stage_high', models.BooleanField(blank=True, default=False, null=True, verbose_name='高点?')),
                ('stage_high_pct', models.FloatField(blank=True, default=False, null=True, verbose_name='高点/买点%?')),
                ('tnx_point', models.BooleanField(blank=True, default=False, null=True, verbose_name='b点?')),
                ('test_strategy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='investors.TradeStrategy', verbose_name='测试策略')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
