# Generated by Django 3.0.2 on 2020-05-14 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0006_auto_20200513_1733'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bstrategytestresultondays',
            options={'ordering': ['ts_code'], 'verbose_name': '交易策略日线测试', 'verbose_name_plural': '交易策略日线测试'},
        ),
        migrations.AddField(
            model_name='tradestrategystat',
            name='code',
            field=models.CharField(default='jz_b', max_length=10, verbose_name='策略代码'),
        ),
        migrations.AlterField(
            model_name='tradestrategystat',
            name='applied_period',
            field=models.CharField(blank=True, choices=[('30', '30分钟'), ('wk', '周线'), ('60', '60分钟'), ('15', '15分钟'), ('dd', '日线'), ('mm', '月线')], default='60', max_length=2, verbose_name='应用周期'),
        ),
    ]
