# Generated by Django 3.0.2 on 2020-05-15 02:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('investors', '0016_auto_20200515_1008'),
        ('analysis', '0009_auto_20200515_0909'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bstrategyonpcttest',
            name='name',
        ),
        migrations.AddField(
            model_name='bstrategyonpcttest',
            name='test_strategy',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='investors.TradeStrategy', verbose_name='测试策略'),
        ),
        migrations.AlterField(
            model_name='tradestrategystat',
            name='applied_period',
            field=models.CharField(blank=True, choices=[('dd', '日线'), ('wk', '周线'), ('30', '30分钟'), ('mm', '月线'), ('15', '15分钟'), ('60', '60分钟')], default='60', max_length=2, verbose_name='应用周期'),
        ),
    ]
