# Generated by Django 3.0.2 on 2020-05-15 02:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('investors', '0017_auto_20200515_1008'),
        ('analysis', '0010_auto_20200515_1008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bstrategyonpcttest',
            name='test_strategy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='investors.TradeStrategy', verbose_name='测试策略'),
        ),
        migrations.AlterField(
            model_name='tradestrategystat',
            name='applied_period',
            field=models.CharField(blank=True, choices=[('30', '30分钟'), ('wk', '周线'), ('60', '60分钟'), ('dd', '日线'), ('15', '15分钟'), ('mm', '月线')], default='60', max_length=2, verbose_name='应用周期'),
        ),
    ]
