# Generated by Django 3.0.2 on 2020-05-16 07:29

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('investors', '0018_auto_20200516_1529'),
        ('analysis', '0011_auto_20200515_1008'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bstrategyonpcttest',
            options={'ordering': ['ts_code'], 'verbose_name': '达到固定涨幅周期', 'verbose_name_plural': '达到固定涨幅周期'},
        ),
        migrations.AlterField(
            model_name='tradestrategystat',
            name='applied_period',
            field=models.CharField(blank=True, choices=[('15', '15分钟'), ('wk', '周线'), ('dd', '日线'), ('30', '30分钟'), ('60', '60分钟'), ('mm', '月线')], default='60', max_length=2, verbose_name='应用周期'),
        ),
        migrations.CreateModel(
            name='BStrategyOnFixedPctTest',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('last_mod_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='最后更新时间')),
                ('ts_code', models.CharField(max_length=15, verbose_name='股票代码')),
                ('trade_date', models.DateField(verbose_name='交易日')),
                ('open', models.FloatField(blank=True, null=True, verbose_name='开盘价')),
                ('high', models.FloatField(blank=True, null=True, verbose_name='最高价')),
                ('low', models.FloatField(blank=True, null=True, verbose_name='最低价')),
                ('pre_close', models.FloatField(blank=True, null=True, verbose_name='前日收盘价')),
                ('close', models.FloatField(blank=True, null=True, verbose_name='收盘价')),
                ('change', models.FloatField(blank=True, null=True, verbose_name='价格变化')),
                ('pct_chg', models.FloatField(blank=True, null=True, verbose_name='涨幅%')),
                ('vol', models.FloatField(blank=True, null=True, verbose_name='交易量')),
                ('amount', models.FloatField(blank=True, null=True, verbose_name='金额')),
                ('pct10_period', models.FloatField(blank=True, default=-1, null=True, verbose_name='+10%最小周期')),
                ('pct20_period', models.FloatField(blank=True, default=-1, null=True, verbose_name='+20%最小周期')),
                ('pct30_period', models.FloatField(blank=True, default=-1, null=True, verbose_name='+30%最小周期')),
                ('pct50_period', models.FloatField(blank=True, default=-1, null=True, verbose_name='+50%最小周期')),
                ('pct80_period', models.FloatField(blank=True, default=-1, null=True, verbose_name='+80%最小周期')),
                ('pct100_period', models.FloatField(blank=True, default=-1, null=True, verbose_name='+100%最小周期')),
                ('pct130_period', models.FloatField(blank=True, default=-1, null=True, verbose_name='+130%最小周期')),
                ('test_freq', models.CharField(default='D', max_length=5, verbose_name='测试周期')),
                ('test_strategy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='investors.TradeStrategy', verbose_name='测试策略')),
            ],
            options={
                'verbose_name': '达到固定涨幅周期',
                'verbose_name_plural': '达到固定涨幅周期',
                'ordering': ['ts_code'],
            },
        ),
    ]
