# Generated by Django 3.0.2 on 2020-05-18 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0013_auto_20200516_2007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tradestrategystat',
            name='applied_period',
            field=models.CharField(blank=True, choices=[('30', '30分钟'), ('wk', '周线'), ('dd', '日线'), ('mm', '月线'), ('60', '60分钟'), ('15', '15分钟')], default='60', max_length=2, verbose_name='应用周期'),
        ),
    ]
