# Generated by Django 3.0.2 on 2020-05-23 13:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0017_auto_20200521_1740'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockstrategytestlog',
            name='cp_marked_dt',
        ),
        migrations.RemoveField(
            model_name='stockstrategytestlog',
            name='cp_update_dt',
        ),
        migrations.RemoveField(
            model_name='stockstrategytestlog',
            name='critical_point_marked',
        ),
        migrations.RemoveField(
            model_name='stockstrategytestlog',
            name='exp_pct_marked',
        ),
        migrations.RemoveField(
            model_name='stockstrategytestlog',
            name='exppct_mark_dt',
        ),
        migrations.RemoveField(
            model_name='stockstrategytestlog',
            name='exppct_mark_update_dt',
        ),
        migrations.RemoveField(
            model_name='stockstrategytestlog',
            name='hist_download_dt',
        ),
        migrations.RemoveField(
            model_name='stockstrategytestlog',
            name='hist_downloaded',
        ),
        migrations.RemoveField(
            model_name='stockstrategytestlog',
            name='hist_update_dt',
        ),
        migrations.RemoveField(
            model_name='stockstrategytestlog',
            name='lhpct_mark_dt',
        ),
        migrations.RemoveField(
            model_name='stockstrategytestlog',
            name='lhpct_update_dt',
        ),
        migrations.RemoveField(
            model_name='stockstrategytestlog',
            name='low_high_pct_marked',
        ),
        migrations.AddField(
            model_name='stockstrategytestlog',
            name='event_type',
            field=models.CharField(choices=[('UPD_LH_PCT', '更新高低点涨幅'), ('MARK_EXP_PCT', '标记预期涨幅'), ('UPD_CP', '更新临界点'), ('UPD_DOWNLOAD', '更新下载历史交易'), ('DOWNLOAD', '下载历史交易'), ('UPD_EXP_PCT', '更新预期涨幅'), ('MARK_LH_PCT', '标记高低点涨幅'), ('MARK_CP', '标记临界点')], default=django.utils.timezone.now, max_length=50, verbose_name='日志类型'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stockstrategytestlog',
            name='is_done',
            field=models.BooleanField(default=True, verbose_name='已完成'),
        ),
        migrations.AlterField(
            model_name='tradestrategystat',
            name='applied_period',
            field=models.CharField(blank=True, choices=[('dd', '日线'), ('60', '60分钟'), ('mm', '月线'), ('wk', '周线'), ('30', '30分钟'), ('15', '15分钟')], default='60', max_length=2, verbose_name='应用周期'),
        ),
    ]
