# Generated by Django 3.0.2 on 2020-05-25 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0024_auto_20200525_1108'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockhistorydaily',
            name='freq',
            field=models.CharField(default='D', max_length=5, verbose_name='周期'),
        ),
        migrations.AlterField(
            model_name='stockstrategytestlog',
            name='event_type',
            field=models.CharField(choices=[('UPD_CP', '更新临界点'), ('UPD_LH_PCT', '更新高低点涨幅'), ('DOWNLOAD', '下载历史交易'), ('UPD_DOWNLOAD', '更新下载历史交易'), ('UPD_EXP_PCT', '更新预期涨幅'), ('MARK_LH_PCT', '标记高低点涨幅'), ('MARK_EXP_PCT', '标记预期涨幅'), ('MARK_CP', '标记临界点')], max_length=50, verbose_name='日志类型'),
        ),
        migrations.AlterField(
            model_name='tradestrategystat',
            name='applied_period',
            field=models.CharField(blank=True, choices=[('15', '15分钟'), ('30', '30分钟'), ('dd', '日线'), ('60', '60分钟'), ('mm', '月线'), ('wk', '周线')], default='60', max_length=2, verbose_name='应用周期'),
        ),
    ]
