# Generated by Django 3.0.2 on 2020-06-07 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0042_auto_20200607_1134'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockstrategytestlog',
            name='strategy',
        ),
        migrations.AddField(
            model_name='stockstrategytestlog',
            name='strategy_code',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='测试策略'),
        ),
        migrations.AlterField(
            model_name='stockstrategytestlog',
            name='event_type',
            field=models.CharField(choices=[('UPD_DOWNLOAD', '更新下载历史交易'), ('DOWNLOAD', '下载历史交易'), ('MARK_CP', '标记临界点'), ('UPD_CP', '更新临界点'), ('PERIOD_UPD', '更新高低点涨幅'), ('PERIOD_TEST', '标记高低点涨幅'), ('EXP_PCT_UPD', '更新预期涨幅'), ('EXP_PCT_TEST', '标记预期涨幅')], max_length=50, verbose_name='日志类型'),
        ),
        migrations.AlterField(
            model_name='tradestrategystat',
            name='applied_period',
            field=models.CharField(blank=True, choices=[('mm', '月线'), ('60', '60分钟'), ('wk', '周线'), ('15', '15分钟'), ('30', '30分钟'), ('dd', '日线')], default='60', max_length=2, null=True, verbose_name='应用周期'),
        ),
    ]
