# Generated by Django 3.0.7 on 2020-06-08 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0047_auto_20200607_1454'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bstrategyonfixedpcttest',
            name='test_strategy',
        ),
        migrations.RemoveField(
            model_name='bstrategyonpcttest',
            name='test_strategy',
        ),
        migrations.RemoveField(
            model_name='bstrategytestresultondays',
            name='test_strategy',
        ),
        migrations.AddField(
            model_name='bstrategyonfixedpcttest',
            name='strategy_code',
            field=models.CharField(blank=True, db_index=True, max_length=25, null=True, verbose_name='策略代码'),
        ),
        migrations.AddField(
            model_name='bstrategyonpcttest',
            name='strategy_code',
            field=models.CharField(blank=True, db_index=True, max_length=25, null=True, verbose_name='策略代码'),
        ),
        migrations.AddField(
            model_name='bstrategytestresultondays',
            name='strategy_code',
            field=models.CharField(blank=True, db_index=True, max_length=25, null=True, verbose_name='策略代码'),
        ),
        migrations.AlterField(
            model_name='stockstrategytestlog',
            name='event_type',
            field=models.CharField(choices=[('DOWNLOAD', '下载历史交易'), ('EXP_PCT_TEST', '标记预期涨幅'), ('MARK_CP', '标记临界点'), ('PERIOD_UPD', '更新高低点涨幅'), ('PERIOD_TEST', '标记高低点涨幅'), ('UPD_DOWNLOAD', '更新下载历史交易'), ('UPD_CP', '更新临界点'), ('EXP_PCT_UPD', '更新预期涨幅')], max_length=50, verbose_name='日志类型'),
        ),
        migrations.AlterField(
            model_name='tradestrategystat',
            name='applied_period',
            field=models.CharField(blank=True, choices=[('60', '60分钟'), ('D', '日线'), ('M', '月线'), ('15', '15分钟'), ('W', '周线'), ('30', '30分钟')], default='60', max_length=2, null=True, verbose_name='应用周期'),
        ),
    ]
