# Generated by Django 3.0.7 on 2020-06-14 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0048_auto_20200608_1058'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockhistorydaily',
            name='dibu_b',
            field=models.BooleanField(blank=True, db_index=True, default=False, null=True, verbose_name='底部B'),
        ),
        migrations.AddField(
            model_name='stockhistorydaily',
            name='dingbu_s',
            field=models.BooleanField(blank=True, db_index=True, default=False, null=True, verbose_name='顶部S'),
        ),
        migrations.AddField(
            model_name='stockhistorydaily',
            name='junxian_zhicheng_b',
            field=models.BooleanField(blank=True, db_index=True, default=False, null=True, verbose_name='均线支撑B'),
        ),
        migrations.AddField(
            model_name='stockhistorydaily',
            name='ma25',
            field=models.FloatField(blank=True, db_index=True, default=-1, null=True, verbose_name='MA25'),
        ),
        migrations.AddField(
            model_name='stockhistorydaily',
            name='slope',
            field=models.FloatField(blank=True, db_index=True, null=True, verbose_name='斜率'),
        ),
        migrations.AddField(
            model_name='stockhistorydaily',
            name='tupo_b',
            field=models.BooleanField(blank=True, db_index=True, default=False, null=True, verbose_name='突破压力位B'),
        ),
        migrations.AlterField(
            model_name='stockhistorydaily',
            name='jiuzhuan_count_b',
            field=models.FloatField(db_index=True, default=-1, verbose_name='九转序列B'),
        ),
        migrations.AlterField(
            model_name='stockhistorydaily',
            name='jiuzhuan_count_s',
            field=models.FloatField(db_index=True, default=-1, verbose_name='九转序列S'),
        ),
        migrations.AlterField(
            model_name='stockstrategytestlog',
            name='event_type',
            field=models.CharField(choices=[('EXP_PCT_TEST', '标记预期涨幅'), ('EXP_PCT_UPD', '更新预期涨幅'), ('UPD_DOWNLOAD', '更新下载历史交易'), ('MARK_CP', '标记临界点'), ('UPD_CP', '更新临界点'), ('PERIOD_TEST', '标记高低点涨幅'), ('DOWNLOAD', '下载历史交易'), ('PERIOD_UPD', '更新高低点涨幅')], max_length=50, verbose_name='日志类型'),
        ),
        migrations.AlterField(
            model_name='tradestrategystat',
            name='applied_period',
            field=models.CharField(blank=True, choices=[('60', '60分钟'), ('30', '30分钟'), ('M', '月线'), ('D', '日线'), ('15', '15分钟'), ('W', '周线')], default='60', max_length=2, null=True, verbose_name='应用周期'),
        ),
    ]
