# Generated by Django 3.0.7 on 2020-06-17 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0049_auto_20200614_0850'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockhistorydaily',
            name='di_min',
            field=models.IntegerField(blank=True, db_index=True, default=0, null=True, verbose_name='底部最低价?'),
        ),
        migrations.AddField(
            model_name='stockhistorydaily',
            name='ding_max',
            field=models.IntegerField(blank=True, db_index=True, default=0, null=True, verbose_name='顶部最高价?'),
        ),
        migrations.AddField(
            model_name='stockhistorydaily',
            name='dingdi_count',
            field=models.IntegerField(blank=True, db_index=True, default=0, null=True, verbose_name='顶底序列'),
        ),
        migrations.AddField(
            model_name='stockhistorydaily',
            name='is_dingdi_last',
            field=models.IntegerField(blank=True, db_index=True, default=0, null=True, verbose_name='顶底结束点?'),
        ),
        migrations.AlterField(
            model_name='stockhistorydaily',
            name='dibu_b',
            field=models.IntegerField(blank=True, db_index=True, default=0, null=True, verbose_name='底部B?'),
        ),
        migrations.AlterField(
            model_name='stockhistorydaily',
            name='dingbu_s',
            field=models.IntegerField(blank=True, db_index=True, default=0, null=True, verbose_name='顶部S?'),
        ),
        migrations.AlterField(
            model_name='stockhistorydaily',
            name='junxian_zhicheng_b',
            field=models.IntegerField(blank=True, db_index=True, default=0, null=True, verbose_name='均线支撑B?'),
        ),
        migrations.AlterField(
            model_name='stockhistorydaily',
            name='tupo_b',
            field=models.IntegerField(blank=True, db_index=True, default=0, null=True, verbose_name='突破压力位B?'),
        ),
        migrations.AlterField(
            model_name='stockstrategytestlog',
            name='event_type',
            field=models.CharField(choices=[('DOWNLOAD', '下载历史交易'), ('UPD_CP', '更新临界点'), ('UPD_DOWNLOAD', '更新下载历史交易'), ('PERIOD_TEST', '标记高低点涨幅'), ('EXP_PCT_TEST', '标记预期涨幅'), ('MARK_CP', '标记临界点'), ('EXP_PCT_UPD', '更新预期涨幅'), ('PERIOD_UPD', '更新高低点涨幅')], max_length=50, verbose_name='日志类型'),
        ),
        migrations.AlterField(
            model_name='tradestrategystat',
            name='applied_period',
            field=models.CharField(blank=True, choices=[('15', '15分钟'), ('W', '周线'), ('M', '月线'), ('60', '60分钟'), ('30', '30分钟'), ('D', '日线')], default='60', max_length=2, null=True, verbose_name='应用周期'),
        ),
    ]
