# Generated by Django 3.0.7 on 2020-06-21 07:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0052_auto_20200617_1352'),
    ]

    operations = [
        migrations.CreateModel(
            name='FocusAreaDuration',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('last_mod_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='最后更新时间')),
                ('ts_code', models.CharField(db_index=True, max_length=15, verbose_name='TS代码')),
                ('trade_date', models.DateField(verbose_name='交易日')),
                ('vol', models.FloatField(blank=True, null=True, verbose_name='交易量')),
                ('amount', models.FloatField(blank=True, null=True, verbose_name='金额')),
                ('duration', models.BooleanField(blank=True, default=False, null=True, verbose_name='周期长度')),
                ('jiuzhuan_count', models.FloatField(blank=True, default=False, null=True, verbose_name='九转点')),
                ('freq', models.CharField(default='D', max_length=5, verbose_name='分析周期')),
                ('strategy_code', models.CharField(blank=True, db_index=True, max_length=25, null=True, verbose_name='策略代码')),
            ],
            options={
                'verbose_name': '关注区周期长度',
                'verbose_name_plural': '关注区周期长度',
                'ordering': ['ts_code'],
            },
        ),
        migrations.AlterField(
            model_name='stockhistorydaily',
            name='di_min',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='底部最低价?'),
        ),
        migrations.AlterField(
            model_name='stockhistorydaily',
            name='dibu_b',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='底部B?'),
        ),
        migrations.AlterField(
            model_name='stockhistorydaily',
            name='ding_max',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='顶部最高价?'),
        ),
        migrations.AlterField(
            model_name='stockhistorydaily',
            name='dingbu_s',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='顶部S?'),
        ),
        migrations.AlterField(
            model_name='stockhistorydaily',
            name='dingdi_count',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='顶底序列'),
        ),
        migrations.AlterField(
            model_name='stockhistorydaily',
            name='is_dingdi_end',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='顶底结束点?'),
        ),
        migrations.AlterField(
            model_name='stockhistorydaily',
            name='junxian_zhicheng_b',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='均线支撑B?'),
        ),
        migrations.AlterField(
            model_name='stockhistorydaily',
            name='ma25',
            field=models.FloatField(blank=True, default=-1, null=True, verbose_name='MA25'),
        ),
        migrations.AlterField(
            model_name='stockhistorydaily',
            name='slope',
            field=models.FloatField(blank=True, null=True, verbose_name='斜率'),
        ),
        migrations.AlterField(
            model_name='stockhistorydaily',
            name='tupo_b',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='突破压力位B?'),
        ),
        migrations.AlterField(
            model_name='stockstrategytestlog',
            name='event_type',
            field=models.CharField(choices=[('DOWNLOAD', '下载历史交易'), ('EXP_PCT_TEST', '标记预期涨幅'), ('PERIOD_TEST', '标记高低点涨幅'), ('PERIOD_UPD', '更新高低点涨幅'), ('EXP_PCT_UPD', '更新预期涨幅'), ('UPD_CP', '更新临界点'), ('UPD_DOWNLOAD', '更新下载历史交易'), ('MARK_CP', '标记临界点')], max_length=50, verbose_name='日志类型'),
        ),
        migrations.AlterField(
            model_name='tradestrategystat',
            name='applied_period',
            field=models.CharField(blank=True, choices=[('W', '周线'), ('15', '15分钟'), ('60', '60分钟'), ('M', '月线'), ('30', '30分钟'), ('D', '日线')], default='60', max_length=2, null=True, verbose_name='应用周期'),
        ),
    ]
