# Generated by Django 3.0.7 on 2020-06-21 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0053_auto_20200621_1557'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stockhistorydaily',
            old_name='junxian_zhicheng_b',
            new_name='ma25_zhicheng_b',
        ),
        migrations.AddField(
            model_name='stockhistorydaily',
            name='ma25_diepo_s',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='均线跌破S?'),
        ),
        migrations.AddField(
            model_name='stockhistorydaily',
            name='ma25_tupo_b',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='均线突破B?'),
        ),
        migrations.AlterField(
            model_name='stockstrategytestlog',
            name='event_type',
            field=models.CharField(choices=[('PERIOD_UPD', '更新高低点涨幅'), ('EXP_PCT_TEST', '标记预期涨幅'), ('PERIOD_TEST', '标记高低点涨幅'), ('DOWNLOAD', '下载历史交易'), ('UPD_CP', '更新临界点'), ('EXP_PCT_UPD', '更新预期涨幅'), ('MARK_CP', '标记临界点'), ('UPD_DOWNLOAD', '更新下载历史交易')], max_length=50, verbose_name='日志类型'),
        ),
        migrations.AlterField(
            model_name='tradestrategystat',
            name='applied_period',
            field=models.CharField(blank=True, choices=[('M', '月线'), ('30', '30分钟'), ('15', '15分钟'), ('D', '日线'), ('W', '周线'), ('60', '60分钟')], default='60', max_length=2, null=True, verbose_name='应用周期'),
        ),
    ]
