# Generated by Django 3.0.7 on 2020-06-21 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0054_auto_20200621_1612'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockhistorydaily',
            name='ding_die_13pct',
            field=models.FloatField(blank=True, null=True, verbose_name='顶部下跌13%'),
        ),
        migrations.AddField(
            model_name='stockhistorydaily',
            name='ding_die_1pct',
            field=models.FloatField(blank=True, null=True, verbose_name='顶部下跌1%'),
        ),
        migrations.AddField(
            model_name='stockhistorydaily',
            name='ding_die_21pct',
            field=models.FloatField(blank=True, null=True, verbose_name='顶部下跌21%'),
        ),
        migrations.AddField(
            model_name='stockhistorydaily',
            name='ding_die_2pct',
            field=models.FloatField(blank=True, null=True, verbose_name='顶部下跌2%'),
        ),
        migrations.AddField(
            model_name='stockhistorydaily',
            name='ding_die_34pct',
            field=models.FloatField(blank=True, null=True, verbose_name='顶部下跌34%'),
        ),
        migrations.AddField(
            model_name='stockhistorydaily',
            name='ding_die_3pct',
            field=models.FloatField(blank=True, null=True, verbose_name='顶部下跌3%'),
        ),
        migrations.AddField(
            model_name='stockhistorydaily',
            name='ding_die_56pct',
            field=models.FloatField(blank=True, null=True, verbose_name='顶部下跌56%'),
        ),
        migrations.AddField(
            model_name='stockhistorydaily',
            name='ding_die_5pct',
            field=models.FloatField(blank=True, null=True, verbose_name='顶部下跌5%'),
        ),
        migrations.AddField(
            model_name='stockhistorydaily',
            name='ding_die_8pct',
            field=models.FloatField(blank=True, null=True, verbose_name='顶部下跌8%'),
        ),
        migrations.AddField(
            model_name='stockhistorydaily',
            name='ding_die_90pct',
            field=models.FloatField(blank=True, null=True, verbose_name='顶部下跌90%'),
        ),
        migrations.AddField(
            model_name='stockhistorydaily',
            name='ma25_yali_s',
            field=models.IntegerField(blank=True, null=True, verbose_name='MA25压力S?'),
        ),
        migrations.AlterField(
            model_name='stockhistorydaily',
            name='is_dingdi_end',
            field=models.IntegerField(blank=True, null=True, verbose_name='顶底结束点?'),
        ),
        migrations.AlterField(
            model_name='stockhistorydaily',
            name='ma25_diepo_s',
            field=models.IntegerField(blank=True, null=True, verbose_name='MA25均线跌破S?'),
        ),
        migrations.AlterField(
            model_name='stockhistorydaily',
            name='ma25_tupo_b',
            field=models.IntegerField(blank=True, null=True, verbose_name='MA25均线突破B?'),
        ),
        migrations.AlterField(
            model_name='stockhistorydaily',
            name='ma25_zhicheng_b',
            field=models.IntegerField(blank=True, null=True, verbose_name='MA25均线支撑B?'),
        ),
        migrations.AlterField(
            model_name='stockhistorydaily',
            name='tupo_b',
            field=models.IntegerField(blank=True, null=True, verbose_name='突破压力位B?'),
        ),
        migrations.AlterField(
            model_name='stockstrategytestlog',
            name='event_type',
            field=models.CharField(choices=[('EXP_PCT_UPD', '更新预期涨幅'), ('UPD_DOWNLOAD', '更新下载历史交易'), ('EXP_PCT_TEST', '标记预期涨幅'), ('PERIOD_TEST', '标记高低点涨幅'), ('DOWNLOAD', '下载历史交易'), ('UPD_CP', '更新临界点'), ('MARK_CP', '标记临界点'), ('PERIOD_UPD', '更新高低点涨幅')], max_length=50, verbose_name='日志类型'),
        ),
        migrations.AlterField(
            model_name='tradestrategystat',
            name='applied_period',
            field=models.CharField(blank=True, choices=[('30', '30分钟'), ('M', '月线'), ('60', '60分钟'), ('15', '15分钟'), ('W', '周线'), ('D', '日线')], default='60', max_length=2, null=True, verbose_name='应用周期'),
        ),
    ]
