# Generated by Django 3.0.7 on 2020-06-25 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0055_auto_20200621_2226'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockhistorydaily',
            name='m_ding',
            field=models.IntegerField(blank=True, null=True, verbose_name='M顶部?'),
        ),
        migrations.AddField(
            model_name='stockhistorydaily',
            name='w_di',
            field=models.IntegerField(blank=True, null=True, verbose_name='W底部?'),
        ),
        migrations.AlterField(
            model_name='stockhistorydaily',
            name='di_min',
            field=models.IntegerField(blank=True, null=True, verbose_name='底部最低价?'),
        ),
        migrations.AlterField(
            model_name='stockhistorydaily',
            name='dibu_b',
            field=models.IntegerField(blank=True, null=True, verbose_name='底部B?'),
        ),
        migrations.AlterField(
            model_name='stockhistorydaily',
            name='ding_max',
            field=models.IntegerField(blank=True, null=True, verbose_name='顶部最高价?'),
        ),
        migrations.AlterField(
            model_name='stockhistorydaily',
            name='dingbu_s',
            field=models.IntegerField(blank=True, null=True, verbose_name='顶部S?'),
        ),
        migrations.AlterField(
            model_name='stockhistorydaily',
            name='dingdi_count',
            field=models.IntegerField(blank=True, null=True, verbose_name='顶底序列'),
        ),
        migrations.AlterField(
            model_name='stockhistorydaily',
            name='jiuzhuan_count_b',
            field=models.FloatField(default=-1, verbose_name='九转序列B'),
        ),
        migrations.AlterField(
            model_name='stockhistorydaily',
            name='jiuzhuan_count_s',
            field=models.FloatField(default=-1, verbose_name='九转序列S'),
        ),
        migrations.AlterField(
            model_name='stockhistorydaily',
            name='ma25',
            field=models.FloatField(blank=True, null=True, verbose_name='MA25'),
        ),
        migrations.AlterField(
            model_name='stockstrategytestlog',
            name='event_type',
            field=models.CharField(choices=[('PERIOD_TEST', '标记高低点涨幅'), ('PERIOD_UPD', '更新高低点涨幅'), ('UPD_DOWNLOAD', '更新下载历史交易'), ('DOWNLOAD', '下载历史交易'), ('UPD_CP', '更新临界点'), ('MARK_CP', '标记临界点'), ('EXP_PCT_UPD', '更新预期涨幅'), ('EXP_PCT_TEST', '标记预期涨幅')], max_length=50, verbose_name='日志类型'),
        ),
        migrations.AlterField(
            model_name='tradestrategystat',
            name='applied_period',
            field=models.CharField(blank=True, choices=[('W', '周线'), ('60', '60分钟'), ('15', '15分钟'), ('M', '月线'), ('30', '30分钟'), ('D', '日线')], default='60', max_length=2, null=True, verbose_name='应用周期'),
        ),
    ]
