# Generated by Django 3.0.7 on 2020-06-25 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0057_auto_20200625_1246'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockhistorydaily',
            name='ding_die_56pct',
        ),
        migrations.RemoveField(
            model_name='stockhistorydaily',
            name='ding_die_90pct',
        ),
        migrations.AddField(
            model_name='stockhistorydaily',
            name='ding_die_55pct',
            field=models.FloatField(blank=True, null=True, verbose_name='顶部下跌55%'),
        ),
        migrations.AddField(
            model_name='stockhistorydaily',
            name='ding_die_89pct',
            field=models.FloatField(blank=True, null=True, verbose_name='顶部下跌89%'),
        ),
        migrations.AlterField(
            model_name='stockstrategytestlog',
            name='event_type',
            field=models.CharField(choices=[('PERIOD_UPD', '更新高低点涨幅'), ('MARK_CP', '标记临界点'), ('UPD_DOWNLOAD', '更新下载历史交易'), ('UPD_CP', '更新临界点'), ('PERIOD_TEST', '标记高低点涨幅'), ('DOWNLOAD', '下载历史交易'), ('EXP_PCT_TEST', '标记预期涨幅'), ('EXP_PCT_UPD', '更新预期涨幅')], max_length=50, verbose_name='日志类型'),
        ),
        migrations.AlterField(
            model_name='tradestrategystat',
            name='applied_period',
            field=models.CharField(blank=True, choices=[('30', '30分钟'), ('D', '日线'), ('15', '15分钟'), ('M', '月线'), ('60', '60分钟'), ('W', '周线')], default='60', max_length=2, null=True, verbose_name='应用周期'),
        ),
    ]
