# Generated by Django 3.0.7 on 2020-06-30 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0065_auto_20200630_1036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockstrategytestlog',
            name='analysis_code',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='测试策略'),
        ),
        migrations.AlterField(
            model_name='stockstrategytestlog',
            name='event_type',
            field=models.CharField(choices=[('DOWNLOAD', '下载历史交易'), ('EXP_PCT_TEST', '标记预期涨幅'), ('UPD_CP', '更新临界点'), ('PERIOD_UPD', '更新高低点涨幅'), ('EXP_PCT_UPD', '更新预期涨幅'), ('MARK_CP', '标记临界点'), ('PERIOD_TEST', '标记高低点涨幅'), ('UPD_DOWNLOAD', '更新下载历史交易')], max_length=50, verbose_name='日志类型'),
        ),
        migrations.AlterField(
            model_name='tradestrategystat',
            name='applied_period',
            field=models.CharField(blank=True, choices=[('W', '周线'), ('15', '15分钟'), ('60', '60分钟'), ('D', '日线'), ('30', '30分钟'), ('M', '月线')], default='60', max_length=2, null=True, verbose_name='应用周期'),
        ),
    ]
