# Generated by Django 3.0.7 on 2020-07-03 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0066_auto_20200630_1040'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockhistorydaily',
            name='ding_die_13pct',
        ),
        migrations.RemoveField(
            model_name='stockhistorydaily',
            name='ding_die_1pct',
        ),
        migrations.RemoveField(
            model_name='stockhistorydaily',
            name='ding_die_21pct',
        ),
        migrations.RemoveField(
            model_name='stockhistorydaily',
            name='ding_die_2pct',
        ),
        migrations.RemoveField(
            model_name='stockhistorydaily',
            name='ding_die_34pct',
        ),
        migrations.RemoveField(
            model_name='stockhistorydaily',
            name='ding_die_3pct',
        ),
        migrations.RemoveField(
            model_name='stockhistorydaily',
            name='ding_die_55pct',
        ),
        migrations.RemoveField(
            model_name='stockhistorydaily',
            name='ding_die_5pct',
        ),
        migrations.RemoveField(
            model_name='stockhistorydaily',
            name='ding_die_89pct',
        ),
        migrations.RemoveField(
            model_name='stockhistorydaily',
            name='ding_die_8pct',
        ),
        migrations.AlterField(
            model_name='stockstrategytestlog',
            name='event_type',
            field=models.CharField(choices=[('UPD_CP', '更新临界点'), ('PERIOD_UPD', '更新高低点涨幅'), ('DOWNLOAD', '下载历史交易'), ('MARK_CP', '标记临界点'), ('PERIOD_TEST', '标记高低点涨幅'), ('EXP_PCT_TEST', '标记预期涨幅'), ('UPD_DOWNLOAD', '更新下载历史交易'), ('EXP_PCT_UPD', '更新预期涨幅')], max_length=50, verbose_name='日志类型'),
        ),
        migrations.AlterField(
            model_name='tradestrategystat',
            name='applied_period',
            field=models.CharField(blank=True, choices=[('W', '周线'), ('60', '60分钟'), ('D', '日线'), ('30', '30分钟'), ('M', '月线'), ('15', '15分钟')], default='60', max_length=2, null=True, verbose_name='应用周期'),
        ),
    ]
