# Generated by Django 3.0.7 on 2020-07-09 02:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0070_auto_20200709_1000'),
    ]

    operations = [
        migrations.CreateModel(
            name='StrategyTestLowHigh',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('ts_code', models.CharField(db_index=True, max_length=15, verbose_name='TS代码')),
                ('trade_date', models.DateField(verbose_name='交易日')),
                ('test_period', models.IntegerField(blank=True, default=10, verbose_name='测试周期长度')),
                ('stage_low_date', models.DateField(blank=True, null=True, verbose_name='低点日期')),
                ('stage_low_pct', models.FloatField(blank=True, null=True, verbose_name='低点/买点%?')),
                ('stage_high_date', models.DateField(blank=True, null=True, verbose_name='高点日期')),
                ('stage_high_pct', models.FloatField(blank=True, null=True, verbose_name='高点/买点%?')),
                ('strategy_code', models.CharField(blank=True, max_length=25, null=True, verbose_name='策略代码')),
            ],
            options={
                'verbose_name': '交易策略日线测试',
                'verbose_name_plural': '交易策略日线测试',
                'ordering': ['ts_code'],
            },
        ),
        migrations.DeleteModel(
            name='BStrategyTestResultOnDays',
        ),
        migrations.AlterField(
            model_name='stockstrategytestlog',
            name='event_type',
            field=models.CharField(choices=[('UPD_DOWNLOAD', '更新下载历史交易'), ('DOWNLOAD', '下载历史交易'), ('PERIOD_TEST', '标记高低点涨幅'), ('UPD_CP', '更新临界点'), ('EXP_PCT_UPD', '更新预期涨幅'), ('MARK_CP', '标记临界点'), ('EXP_PCT_TEST', '标记预期涨幅'), ('PERIOD_UPD', '更新高低点涨幅')], max_length=50, verbose_name='日志类型'),
        ),
        migrations.AlterField(
            model_name='tradestrategystat',
            name='applied_period',
            field=models.CharField(blank=True, choices=[('D', '日线'), ('M', '月线'), ('W', '周线'), ('15', '15分钟'), ('30', '30分钟'), ('60', '60分钟')], default='60', max_length=2, null=True, verbose_name='应用周期'),
        ),
    ]
