# Generated by Django 3.0.2 on 2020-09-06 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0072_auto_20200714_2144'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarkCriticalPointTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='stockstrategytestlog',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='结束日期'),
        ),
        migrations.AddField(
            model_name='stockstrategytestlog',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='开始日期'),
        ),
        migrations.AlterField(
            model_name='stockstrategytestlog',
            name='event_type',
            field=models.CharField(choices=[('DOWNLOAD', '下载历史交易'), ('UPD_CP', '更新临界点'), ('EXP_PCT_UPD', '更新预期涨幅'), ('PERIOD_TEST', '标记高低点涨幅'), ('MARK_CP', '标记临界点'), ('UPD_DOWNLOAD', '更新下载历史交易'), ('EXP_PCT_TEST', '标记预期涨幅'), ('PERIOD_UPD', '更新高低点涨幅')], max_length=50, verbose_name='日志类型'),
        ),
        migrations.AlterField(
            model_name='stockstrategytestlog',
            name='is_done',
            field=models.BooleanField(default=False, verbose_name='已完成'),
        ),
        migrations.AlterField(
            model_name='tradestrategystat',
            name='applied_period',
            field=models.CharField(blank=True, choices=[('W', '周线'), ('30', '30分钟'), ('15', '15分钟'), ('M', '月线'), ('60', '60分钟'), ('D', '日线')], default='60', max_length=2, null=True, verbose_name='应用周期'),
        ),
    ]
