# Generated by Django 3.0.7 on 2020-09-10 13:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0075_auto_20200906_2117'),
    ]

    operations = [
        migrations.CreateModel(
            name='StrategyTargetPctTestQuantiles',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('last_mod_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='最后更新时间')),
                ('strategy_code', models.CharField(blank=True, db_index=True, max_length=25, null=True, verbose_name='策略代码')),
                ('ts_code', models.CharField(max_length=15, verbose_name='股票代码')),
                ('qt_10pct', models.FloatField(blank=True, null=True, verbose_name='10%分位数')),
                ('qt_25pct', models.FloatField(blank=True, null=True, verbose_name='25%分位数')),
                ('qt_50pct', models.FloatField(blank=True, null=True, verbose_name='50%分位数')),
                ('qt_75pct', models.FloatField(blank=True, null=True, verbose_name='75%分位数')),
                ('qt_90pct', models.FloatField(blank=True, null=True, verbose_name='90%分位数')),
                ('mean_val', models.FloatField(blank=True, null=True, verbose_name='平均数')),
                ('min_val', models.FloatField(blank=True, null=True, verbose_name='最小值')),
                ('max_val', models.FloatField(blank=True, null=True, verbose_name='最大值')),
                ('target_pct', models.IntegerField(verbose_name='目标涨幅')),
                ('ranking', models.IntegerField(blank=True, db_index=True, null=True, verbose_name='排名')),
                ('test_freq', models.CharField(default='D', max_length=5, verbose_name='K线周期')),
            ],
            options={
                'verbose_name': '目标涨幅四分位统计',
                'verbose_name_plural': '目标涨幅四分位统计',
                'ordering': ['ts_code'],
            },
        ),
        migrations.CreateModel(
            name='StrategyUpDownTestQuantiles',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('last_mod_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='最后更新时间')),
                ('strategy_code', models.CharField(blank=True, db_index=True, max_length=25, null=True, verbose_name='策略代码')),
                ('test_type', models.CharField(blank=True, max_length=25, null=True, verbose_name='测试类型')),
                ('ts_code', models.CharField(max_length=15, verbose_name='股票代码')),
                ('qt_10pct', models.FloatField(blank=True, null=True, verbose_name='10%分位数')),
                ('qt_25pct', models.FloatField(blank=True, null=True, verbose_name='25%分位数')),
                ('qt_50pct', models.FloatField(blank=True, null=True, verbose_name='50%分位数')),
                ('qt_75pct', models.FloatField(blank=True, null=True, verbose_name='75%分位数')),
                ('qt_90pct', models.FloatField(blank=True, null=True, verbose_name='90%分位数')),
                ('mean_val', models.FloatField(blank=True, null=True, verbose_name='平均数')),
                ('min_val', models.FloatField(blank=True, null=True, verbose_name='最小值')),
                ('max_val', models.FloatField(blank=True, null=True, verbose_name='最大值')),
                ('test_period', models.IntegerField(verbose_name='测试周期')),
                ('ranking', models.IntegerField(db_index=True, verbose_name='排名')),
                ('test_freq', models.CharField(default='D', max_length=5, verbose_name='K线周期')),
            ],
            options={
                'verbose_name': '涨跌四分位统计',
                'verbose_name_plural': '涨跌四分位统计',
                'ordering': ['ts_code'],
            },
        ),
        migrations.AlterField(
            model_name='stockstrategytestlog',
            name='event_type',
            field=models.CharField(choices=[('MARK_CP', '标记临界点'), ('UPD_DOWNLOAD', '更新下载历史交易'), ('DOWNLOAD', '下载历史交易'), ('UPD_CP', '更新临界点'), ('EXP_PCT_UPD', '更新预期涨幅'), ('PERIOD_TEST', '标记高低点涨幅'), ('EXP_PCT_TEST', '标记预期涨幅'), ('PERIOD_UPD', '更新高低点涨幅')], max_length=50, verbose_name='日志类型'),
        ),
        migrations.AlterField(
            model_name='tradestrategystat',
            name='applied_period',
            field=models.CharField(blank=True, choices=[('60', '60分钟'), ('D', '日线'), ('30', '30分钟'), ('15', '15分钟'), ('M', '月线'), ('W', '周线')], default='60', max_length=2, null=True, verbose_name='应用周期'),
        ),
    ]
