# Generated by Django 3.0.7 on 2020-09-10 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0077_auto_20200910_2158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockstrategytestlog',
            name='event_type',
            field=models.CharField(choices=[('UPD_DOWNLOAD', '更新下载历史交易'), ('UPD_CP', '更新临界点'), ('PERIOD_TEST', '标记高低点涨幅'), ('EXP_PCT_UPD', '更新预期涨幅'), ('EXP_PCT_TEST', '标记预期涨幅'), ('MARK_CP', '标记临界点'), ('PERIOD_UPD', '更新高低点涨幅'), ('DOWNLOAD', '下载历史交易')], max_length=50, verbose_name='日志类型'),
        ),
        migrations.AlterField(
            model_name='strategytargetpcttestquantiles',
            name='target_pct',
            field=models.CharField(max_length=25, verbose_name='目标涨幅'),
        ),
        migrations.AlterField(
            model_name='tradestrategystat',
            name='applied_period',
            field=models.CharField(blank=True, choices=[('M', '月线'), ('60', '60分钟'), ('30', '30分钟'), ('W', '周线'), ('D', '日线'), ('15', '15分钟')], default='60', max_length=2, null=True, verbose_name='应用周期'),
        ),
    ]
