# Generated by Django 3.0.7 on 2020-09-22 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0085_auto_20200922_1950'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockhistorydaily',
            name='ma200',
            field=models.FloatField(blank=True, null=True, verbose_name='MA200'),
        ),
        migrations.AddField(
            model_name='stockhistorydaily',
            name='ma60',
            field=models.FloatField(blank=True, null=True, verbose_name='MA60'),
        ),
        migrations.AlterField(
            model_name='stockstrategytestlog',
            name='event_type',
            field=models.CharField(choices=[('UPD_CP', '更新临界点'), ('EXP_PCT_TEST', '标记预期涨幅'), ('PERIOD_TEST', '标记高低点涨幅'), ('DOWNLOAD', '下载历史交易'), ('MARK_CP', '标记临界点'), ('UPD_DOWNLOAD', '更新下载历史交易'), ('PERIOD_UPD', '更新高低点涨幅'), ('EXP_PCT_UPD', '更新预期涨幅')], max_length=50, verbose_name='日志类型'),
        ),
        migrations.AlterField(
            model_name='tradestrategystat',
            name='applied_period',
            field=models.CharField(blank=True, choices=[('60', '60分钟'), ('15', '15分钟'), ('M', '月线'), ('D', '日线'), ('W', '周线'), ('30', '30分钟')], default='60', max_length=2, null=True, verbose_name='应用周期'),
        ),
    ]
