# Generated by Django 3.0.7 on 2020-10-01 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0086_auto_20200922_2003'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockhistorydaily',
            name='ma200_diepo_v1',
            field=models.IntegerField(blank=True, null=True, verbose_name='MA200均线跌破S?'),
        ),
        migrations.AddField(
            model_name='stockhistorydaily',
            name='ma200_tupo_v1',
            field=models.IntegerField(blank=True, null=True, verbose_name='MA200均线突破B?'),
        ),
        migrations.AddField(
            model_name='stockhistorydaily',
            name='ma200_yali_v1',
            field=models.IntegerField(blank=True, null=True, verbose_name='MA200压力S?'),
        ),
        migrations.AddField(
            model_name='stockhistorydaily',
            name='ma200_zhicheng_v1',
            field=models.IntegerField(blank=True, null=True, verbose_name='MA200均线支撑B?'),
        ),
        migrations.AddField(
            model_name='stockhistorydaily',
            name='ma60_diepo_v1',
            field=models.IntegerField(blank=True, null=True, verbose_name='MA60均线跌破S?'),
        ),
        migrations.AddField(
            model_name='stockhistorydaily',
            name='ma60_tupo_v1',
            field=models.IntegerField(blank=True, null=True, verbose_name='MA60均线突破B?'),
        ),
        migrations.AddField(
            model_name='stockhistorydaily',
            name='ma60_yali_v1',
            field=models.IntegerField(blank=True, null=True, verbose_name='MA60压力S?'),
        ),
        migrations.AddField(
            model_name='stockhistorydaily',
            name='ma60_zhicheng_v1',
            field=models.IntegerField(blank=True, null=True, verbose_name='MA60均线支撑B?'),
        ),
        migrations.AlterField(
            model_name='stockstrategytestlog',
            name='event_type',
            field=models.CharField(choices=[('MARK_CP', '标记临界点'), ('EXP_PCT_TEST', '标记预期涨幅'), ('PERIOD_TEST', '标记高低点涨幅'), ('EXP_PCT_UPD', '更新预期涨幅'), ('PERIOD_UPD', '更新高低点涨幅'), ('UPD_DOWNLOAD', '更新下载历史交易'), ('DOWNLOAD', '下载历史交易'), ('UPD_CP', '更新临界点')], max_length=50, verbose_name='日志类型'),
        ),
        migrations.AlterField(
            model_name='tradestrategystat',
            name='applied_period',
            field=models.CharField(blank=True, choices=[('W', '周线'), ('D', '日线'), ('15', '15分钟'), ('30', '30分钟'), ('60', '60分钟'), ('M', '月线')], default='60', max_length=2, null=True, verbose_name='应用周期'),
        ),
    ]
