# Generated by Django 3.0.7 on 2021-04-09 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0095_auto_20210320_1533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockstrategytestlog',
            name='event_type',
            field=models.CharField(choices=[('PERIOD_TEST', '标记高低点涨幅'), ('UPD_CP', '更新临界点'), ('DOWNLOAD', '下载历史交易'), ('UPD_DOWNLOAD', '更新下载历史交易'), ('EXP_PCT_UPD', '更新预期涨幅'), ('EXP_PCT_TEST', '标记预期涨幅'), ('MARK_CP', '标记临界点'), ('PERIOD_UPD', '更新高低点涨幅')], max_length=50, verbose_name='日志类型'),
        ),
        migrations.AlterField(
            model_name='strategytestlowhigh',
            name='strategy_code',
            field=models.CharField(blank=True, db_index=True, max_length=25, null=True, verbose_name='策略代码'),
        ),
        migrations.AlterField(
            model_name='tradestrategystat',
            name='applied_period',
            field=models.CharField(blank=True, choices=[('60', '60分钟'), ('30', '30分钟'), ('D', '日线'), ('M', '月线'), ('15', '15分钟'), ('W', '周线')], default='60', max_length=2, null=True, verbose_name='应用周期'),
        ),
    ]
