# Generated by Django 3.0.2 on 2021-09-01 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0098_auto_20210410_0914'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BStrategyOnFixedPctTest',
        ),
        migrations.DeleteModel(
            name='BStrategyOnPctTest',
        ),
        migrations.DeleteModel(
            name='FocusAreaDuration',
        ),
        migrations.RemoveField(
            model_name='pickedstocksmeetstrategy',
            name='done_by',
        ),
        migrations.DeleteModel(
            name='StrategyOnDownPctTest',
        ),
        migrations.DeleteModel(
            name='StrategyOnFixedDownPctTest',
        ),
        migrations.RemoveField(
            model_name='strategytargetpcttestquantiles',
            name='company',
        ),
        migrations.RemoveField(
            model_name='strategytargetpcttestquantiles',
            name='company_basic',
        ),
        migrations.DeleteModel(
            name='StrategyTargetPctTestRanking',
        ),
        migrations.DeleteModel(
            name='StrategyTestLowHigh',
        ),
        migrations.RemoveField(
            model_name='strategyupdowntestquantiles',
            name='company',
        ),
        migrations.RemoveField(
            model_name='strategyupdowntestquantiles',
            name='company_basic',
        ),
        migrations.DeleteModel(
            name='StrategyUpDownTestRanking',
        ),
        migrations.RemoveField(
            model_name='tradestrategystat',
            name='creator',
        ),
        migrations.AlterField(
            model_name='stockstrategytestlog',
            name='event_type',
            field=models.CharField(choices=[('EXP_PCT_TEST', '标记预期涨幅'), ('PERIOD_TEST', '标记高低点涨幅'), ('UPD_DOWNLOAD', '更新下载历史交易'), ('PERIOD_UPD', '更新高低点涨幅'), ('EXP_PCT_UPD', '更新预期涨幅'), ('MARK_CP', '标记临界点'), ('UPD_CP', '更新临界点'), ('DOWNLOAD', '下载历史交易')], max_length=50, verbose_name='日志类型'),
        ),
        migrations.DeleteModel(
            name='PickedStocksMeetStrategy',
        ),
        migrations.DeleteModel(
            name='StrategyTargetPctTestQuantiles',
        ),
        migrations.DeleteModel(
            name='StrategyUpDownTestQuantiles',
        ),
        migrations.DeleteModel(
            name='TradeStrategyStat',
        ),
    ]
