# Generated by Django 3.0.2 on 2021-09-08 13:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0099_auto_20210901_2050'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockQuantileStat',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('last_mod_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='最后更新时间')),
                ('ts_code', models.CharField(db_index=True, max_length=15, verbose_name='TS代码')),
                ('stat_type', models.CharField(blank=True, max_length=10, null=True, verbose_name='统计类型')),
                ('period', models.IntegerField(blank=True, null=True, verbose_name='统计周期')),
                ('quatile', models.IntegerField(blank=True, null=True, verbose_name='分位数')),
                ('price', models.FloatField(blank=True, null=True, verbose_name='股价')),
                ('freq', models.CharField(default='D', max_length=5, verbose_name='分析周期')),
            ],
            options={
                'verbose_name': '股票高低分位统计',
                'verbose_name_plural': '股票高低分位统计',
                'ordering': ['-last_mod_time'],
                'get_latest_by': 'id',
            },
        ),
        migrations.AlterField(
            model_name='stockstrategytestlog',
            name='event_type',
            field=models.CharField(choices=[('UPD_DOWNLOAD', '更新下载历史交易'), ('UPD_CP', '更新临界点'), ('PERIOD_UPD', '更新高低点涨幅'), ('MARK_CP', '标记临界点'), ('DOWNLOAD', '下载历史交易'), ('EXP_PCT_TEST', '标记预期涨幅'), ('PERIOD_TEST', '标记高低点涨幅'), ('EXP_PCT_UPD', '更新预期涨幅')], max_length=50, verbose_name='日志类型'),
        ),
    ]
