# Generated by Django 3.0.2 on 2021-09-11 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0101_auto_20210911_1538'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stockquantilestat',
            old_name='quatile',
            new_name='quantile',
        ),
        migrations.AlterField(
            model_name='stockstrategytestlog',
            name='event_type',
            field=models.CharField(choices=[('EXP_PCT_TEST', '标记预期涨幅'), ('UPD_CP', '更新临界点'), ('DOWNLOAD', '下载历史交易'), ('MARK_CP', '标记临界点'), ('EXP_PCT_UPD', '更新预期涨幅'), ('PERIOD_UPD', '更新高低点涨幅'), ('PERIOD_TEST', '标记高低点涨幅'), ('UPD_DOWNLOAD', '更新下载历史交易')], max_length=50, verbose_name='日志类型'),
        ),
    ]
