# Generated by Django 3.0.2 on 2021-09-25 02:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0102_auto_20210911_1632'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisDateSeq',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('last_mod_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='最后更新时间')),
                ('seq_type', models.CharField(blank=True, db_index=True, max_length=15, null=True, verbose_name='统计类型')),
                ('analysis_date', models.DateField(blank=True, null=True, verbose_name='统计日期')),
            ],
            options={
                'verbose_name': '分析日期',
                'verbose_name_plural': '分析日期',
                'ordering': ['-last_mod_time'],
                'get_latest_by': 'id',
            },
        ),
        migrations.CreateModel(
            name='IndustryBasicQuantileStat',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('last_mod_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='最后更新时间')),
                ('industry', models.CharField(db_index=True, max_length=15, verbose_name='行业')),
                ('basic_type', models.CharField(blank=True, max_length=10, null=True, verbose_name='统计类型')),
                ('quantile', models.FloatField(blank=True, null=True, verbose_name='分位数')),
                ('stk_quantity', models.IntegerField(blank=True, null=True, verbose_name='股票数')),
                ('snap_date', models.DateField(blank=True, null=True, verbose_name='分析时间')),
            ],
            options={
                'verbose_name': '行业高低分位统计',
                'verbose_name_plural': '行业高低分位统计',
                'ordering': ['-last_mod_time'],
                'get_latest_by': 'id',
            },
        ),
        migrations.AlterField(
            model_name='stockstrategytestlog',
            name='event_type',
            field=models.CharField(choices=[('UPD_CP', '更新临界点'), ('EXP_PCT_UPD', '更新预期涨幅'), ('UPD_DOWNLOAD', '更新下载历史交易'), ('DOWNLOAD', '下载历史交易'), ('PERIOD_TEST', '标记高低点涨幅'), ('MARK_CP', '标记临界点'), ('PERIOD_UPD', '更新高低点涨幅'), ('EXP_PCT_TEST', '标记预期涨幅')], max_length=50, verbose_name='日志类型'),
        ),
    ]
