# Generated by Django 3.0.2 on 2021-09-25 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0104_auto_20210925_1045'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysisdateseq',
            name='applied',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='已应用'),
        ),
        migrations.AlterField(
            model_name='stockstrategytestlog',
            name='event_type',
            field=models.CharField(choices=[('UPD_DOWNLOAD', '更新下载历史交易'), ('UPD_CP', '更新临界点'), ('EXP_PCT_TEST', '标记预期涨幅'), ('MARK_CP', '标记临界点'), ('PERIOD_UPD', '更新高低点涨幅'), ('DOWNLOAD', '下载历史交易'), ('PERIOD_TEST', '标记高低点涨幅'), ('EXP_PCT_UPD', '更新预期涨幅')], max_length=50, verbose_name='日志类型'),
        ),
        migrations.AlterUniqueTogether(
            name='analysisdateseq',
            unique_together={('seq_type', 'analysis_date')},
        ),
    ]
