# Generated by Django 3.0.2 on 2021-10-17 13:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stockmarket', '0030_companydailybasicext_industry'),
        ('analysis', '0107_auto_20211009_1553'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stockhistorydaily',
            options={'get_latest_by': 'id', 'ordering': ['-trade_date'], 'verbose_name': '股票代码表', 'verbose_name_plural': '股票代码表'},
        ),
        migrations.AlterModelOptions(
            name='stockhistorydailyarc',
            options={'get_latest_by': 'id', 'ordering': ['-last_mod_time'], 'verbose_name': '股票收盘备份', 'verbose_name_plural': '股票收盘备份'},
        ),
        migrations.AddField(
            model_name='stockhistorydaily',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='close_history', to='stockmarket.StockNameCodeMap'),
        ),
        migrations.AlterField(
            model_name='stockstrategytestlog',
            name='event_type',
            field=models.CharField(choices=[('EXP_PCT_TEST', '标记预期涨幅'), ('PERIOD_TEST', '标记高低点涨幅'), ('MARK_CP', '标记临界点'), ('EXP_PCT_UPD', '更新预期涨幅'), ('PERIOD_UPD', '更新高低点涨幅'), ('UPD_DOWNLOAD', '更新下载历史交易'), ('DOWNLOAD', '下载历史交易'), ('UPD_CP', '更新临界点')], max_length=50, verbose_name='日志类型'),
        ),
    ]
