# Generated by Django 3.0.2 on 2021-10-23 09:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stockmarket', '0032_auto_20211021_1312'),
        ('analysis', '0108_auto_20211017_2130'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='industrybasicquantilestat',
            options={'get_latest_by': 'id', 'ordering': ['-snap_date'], 'verbose_name': '行业高低分位统计', 'verbose_name_plural': '行业高低分位统计'},
        ),
        migrations.AddField(
            model_name='industrybasicquantilestat',
            name='ind',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='industry_basic', to='stockmarket.Industry'),
        ),
        migrations.AlterField(
            model_name='stockstrategytestlog',
            name='event_type',
            field=models.CharField(choices=[('DOWNLOAD', '下载历史交易'), ('EXP_PCT_TEST', '标记预期涨幅'), ('PERIOD_UPD', '更新高低点涨幅'), ('UPD_DOWNLOAD', '更新下载历史交易'), ('PERIOD_TEST', '标记高低点涨幅'), ('MARK_CP', '标记临界点'), ('EXP_PCT_UPD', '更新预期涨幅'), ('UPD_CP', '更新临界点')], max_length=50, verbose_name='日志类型'),
        ),
    ]
