# Generated by Django 3.0.2 on 2021-11-21 13:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stockmarket', '0037_companybasicfilter'),
        ('analysis', '0109_auto_20211023_1732'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockindexhistory',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='index_history', to='stockmarket.StockNameCodeMap'),
        ),
        migrations.AlterField(
            model_name='stockstrategytestlog',
            name='event_type',
            field=models.CharField(choices=[('PERIOD_TEST', '标记高低点涨幅'), ('EXP_PCT_TEST', '标记预期涨幅'), ('EXP_PCT_UPD', '更新预期涨幅'), ('DOWNLOAD', '下载历史交易'), ('UPD_DOWNLOAD', '更新下载历史交易'), ('PERIOD_UPD', '更新高低点涨幅'), ('MARK_CP', '标记临界点'), ('UPD_CP', '更新临界点')], max_length=50, verbose_name='日志类型'),
        ),
    ]
