# Generated by Django 3.2.10 on 2022-04-26 09:07

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('stockmarket', '0051_stocknamecodemap_pop2eema_date'),
        ('analysis', '0111_auto_20220420_2120'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockHistory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('last_mod_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='最后更新时间')),
                ('ts_code', models.CharField(db_index=True, max_length=15, verbose_name='TS代码')),
                ('trade_date', models.DateField(max_length=6, verbose_name='交易日')),
                ('open', models.FloatField(blank=True, null=True, verbose_name='开盘价')),
                ('high', models.FloatField(blank=True, null=True, verbose_name='最高价')),
                ('low', models.FloatField(blank=True, null=True, verbose_name='最低价')),
                ('pre_close', models.FloatField(blank=True, null=True, verbose_name='前日收盘价')),
                ('close', models.FloatField(blank=True, null=True, verbose_name='收盘价')),
                ('change', models.FloatField(blank=True, null=True, verbose_name='价格变化')),
                ('pct_chg', models.FloatField(blank=True, null=True, verbose_name='价格变化%')),
                ('vol', models.FloatField(blank=True, null=True, verbose_name='交易量')),
                ('amount', models.FloatField(blank=True, null=True, verbose_name='金额')),
                ('chg4', models.FloatField(blank=True, null=True, verbose_name='与4日前变化')),
                ('jiuzhuan_count_b', models.FloatField(blank=True, null=True, verbose_name='九转序列B')),
                ('jiuzhuan_count_s', models.FloatField(blank=True, null=True, verbose_name='九转序列S')),
                ('freq', models.CharField(default='W', max_length=5, verbose_name='周期')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_history', to='stockmarket.stocknamecodemap')),
            ],
            options={
                'verbose_name': '股票代码表',
                'verbose_name_plural': '股票代码表',
                'ordering': ['-trade_date'],
                'get_latest_by': 'id',
            },
        ),
        migrations.CreateModel(
            name='StockHistoryIndicators',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('last_mod_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='最后更新时间')),
                ('ts_code', models.CharField(db_index=True, max_length=15, verbose_name='TS代码')),
                ('trade_date', models.DateField(max_length=6, verbose_name='交易日')),
                ('high', models.FloatField(blank=True, null=True, verbose_name='最高价')),
                ('low', models.FloatField(blank=True, null=True, verbose_name='最低价')),
                ('close', models.FloatField(blank=True, null=True, verbose_name='收盘价')),
                ('vol', models.FloatField(blank=True, null=True, verbose_name='交易量')),
                ('amount', models.FloatField(blank=True, null=True, verbose_name='金额')),
                ('var1', models.FloatField(blank=True, null=True, verbose_name='九转序列B')),
                ('var2', models.FloatField(blank=True, null=True, verbose_name='九转序列S')),
                ('var3', models.FloatField(blank=True, null=True, verbose_name='MA25')),
                ('rsv', models.FloatField(blank=True, null=True, verbose_name='MA25斜率')),
                ('eema_b', models.FloatField(blank=True, null=True, verbose_name='MA60')),
                ('eema_s', models.FloatField(blank=True, null=True, verbose_name='MA60斜率')),
                ('freq', models.CharField(default='D', max_length=5, verbose_name='周期')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eema_indicator_history', to='stockmarket.stocknamecodemap')),
            ],
            options={
                'verbose_name': '股票技术指标',
                'verbose_name_plural': '股票技术指标',
                'ordering': ['-trade_date'],
                'get_latest_by': 'id',
            },
        ),
        migrations.AlterField(
            model_name='stockstrategytestlog',
            name='event_type',
            field=models.CharField(choices=[('MARK_CP', '标记临界点'), ('EXP_PCT_TEST', '标记预期涨幅'), ('EXP_PCT_UPD', '更新预期涨幅'), ('PERIOD_TEST', '标记高低点涨幅'), ('UPD_CP', '更新临界点'), ('DOWNLOAD', '下载历史交易'), ('UPD_DOWNLOAD', '更新下载历史交易'), ('PERIOD_UPD', '更新高低点涨幅')], max_length=50, verbose_name='日志类型'),
        ),
        migrations.DeleteModel(
            name='IndicatorEEMA',
        ),
    ]
