# Generated by Django 4.1 on 2022-09-18 06:43

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('stockmarket', '0054_stocknamecodemap_pop2eema_date_m_and_more'),
        ('analysis', '0112_auto_20220426_1707'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyTechIndicatorFilters',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('last_mod_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='最后更新时间')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='stockhistoryindicators',
            name='eema_b',
            field=models.FloatField(blank=True, null=True, verbose_name='b'),
        ),
        migrations.AlterField(
            model_name='stockhistoryindicators',
            name='eema_s',
            field=models.FloatField(blank=True, null=True, verbose_name='s'),
        ),
        migrations.AlterField(
            model_name='stockhistoryindicators',
            name='rsv',
            field=models.FloatField(blank=True, null=True, verbose_name='rsv'),
        ),
        migrations.AlterField(
            model_name='stockhistoryindicators',
            name='var1',
            field=models.FloatField(blank=True, null=True, verbose_name='var1'),
        ),
        migrations.AlterField(
            model_name='stockhistoryindicators',
            name='var2',
            field=models.FloatField(blank=True, null=True, verbose_name='var2'),
        ),
        migrations.AlterField(
            model_name='stockhistoryindicators',
            name='var3',
            field=models.FloatField(blank=True, null=True, verbose_name='var3'),
        ),
        migrations.AlterField(
            model_name='stockstrategytestlog',
            name='event_type',
            field=models.CharField(choices=[('UPD_CP', '更新临界点'), ('PERIOD_UPD', '更新高低点涨幅'), ('MARK_CP', '标记临界点'), ('EXP_PCT_TEST', '标记预期涨幅'), ('DOWNLOAD', '下载历史交易'), ('PERIOD_TEST', '标记高低点涨幅'), ('EXP_PCT_UPD', '更新预期涨幅'), ('UPD_DOWNLOAD', '更新下载历史交易')], max_length=50, verbose_name='日志类型'),
        ),
        migrations.CreateModel(
            name='StockHistoryIndicatorFilters',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('last_mod_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='最后更新时间')),
                ('ts_code', models.CharField(db_index=True, max_length=15, verbose_name='TS代码')),
                ('trade_date', models.DateField(max_length=6, verbose_name='交易日')),
                ('var1', models.FloatField(blank=True, null=True, verbose_name='var1')),
                ('var2', models.FloatField(blank=True, null=True, verbose_name='var2')),
                ('var3', models.FloatField(blank=True, null=True, verbose_name='var3')),
                ('rsv', models.FloatField(blank=True, null=True, verbose_name='rsv')),
                ('eema_b', models.FloatField(blank=True, null=True, verbose_name='b')),
                ('eema_s', models.FloatField(blank=True, null=True, verbose_name='s')),
                ('freq', models.CharField(default='D', max_length=5, verbose_name='周期')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='indicator_filter', to='stockmarket.stocknamecodemap')),
            ],
            options={
                'verbose_name': '股票技术指标',
                'verbose_name_plural': '股票技术指标',
                'ordering': ['-trade_date'],
                'get_latest_by': 'id',
            },
        ),
    ]
