# Generated by Django 4.1 on 2022-12-15 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0113_companytechindicatorfilters_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockhistorydaily',
            name='ma200',
        ),
        migrations.RemoveField(
            model_name='stockhistorydaily',
            name='ma200_slope',
        ),
        migrations.RemoveField(
            model_name='stockhistorydaily',
            name='ma25',
        ),
        migrations.RemoveField(
            model_name='stockhistorydaily',
            name='ma25_slope',
        ),
        migrations.RemoveField(
            model_name='stockhistorydaily',
            name='ma60',
        ),
        migrations.RemoveField(
            model_name='stockhistorydaily',
            name='ma60_slope',
        ),
        migrations.RemoveField(
            model_name='stockhistorydaily',
            name='slope',
        ),
        migrations.AddField(
            model_name='stockhistorydaily',
            name='change_qfq',
            field=models.FloatField(blank=True, null=True, verbose_name='价格变化_qfq'),
        ),
        migrations.AddField(
            model_name='stockhistorydaily',
            name='close_qfq',
            field=models.FloatField(blank=True, null=True, verbose_name='收盘价_qfq'),
        ),
        migrations.AddField(
            model_name='stockhistorydaily',
            name='high_qfq',
            field=models.FloatField(blank=True, null=True, verbose_name='最高价_qfq'),
        ),
        migrations.AddField(
            model_name='stockhistorydaily',
            name='low_qfq',
            field=models.FloatField(blank=True, null=True, verbose_name='最低价_qfq'),
        ),
        migrations.AddField(
            model_name='stockhistorydaily',
            name='open_qfq',
            field=models.FloatField(blank=True, null=True, verbose_name='开盘价_qfq'),
        ),
        migrations.AddField(
            model_name='stockhistorydaily',
            name='pct_chg_qfq',
            field=models.FloatField(blank=True, null=True, verbose_name='价格变化%_qfq'),
        ),
        migrations.AddField(
            model_name='stockhistorydaily',
            name='pre_close_qfq',
            field=models.FloatField(blank=True, null=True, verbose_name='前日收盘价_qfq'),
        ),
        migrations.AlterField(
            model_name='stockstrategytestlog',
            name='event_type',
            field=models.CharField(choices=[('EXP_PCT_TEST', '标记预期涨幅'), ('EXP_PCT_UPD', '更新预期涨幅'), ('UPD_DOWNLOAD', '更新下载历史交易'), ('MARK_CP', '标记临界点'), ('UPD_CP', '更新临界点'), ('DOWNLOAD', '下载历史交易'), ('PERIOD_TEST', '标记高低点涨幅'), ('PERIOD_UPD', '更新高低点涨幅')], max_length=50, verbose_name='日志类型'),
        ),
    ]
