# Generated by Django 3.0.2 on 2020-04-19 12:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StockNameCodeMap',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('last_mod_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='最后更新时间')),
                ('market', models.CharField(blank=True, choices=[('ZB', '主板'), ('ZXB', '中小板'), ('CYB', '创业板'), ('KCB', '科创板')], max_length=50, null=True, verbose_name='市场类型')),
                ('stock_name', models.CharField(max_length=50, unique=True, verbose_name='股票名称')),
                ('stock_code', models.CharField(max_length=50, unique=True, verbose_name='股票代码')),
                ('exchange', models.CharField(blank=True, choices=[('SSE', '上交所'), ('SZSE', '深交所')], max_length=10, null=True, verbose_name='交易所代码')),
                ('ts_code', models.CharField(blank=True, max_length=50, verbose_name='TS代码')),
                ('area', models.CharField(blank=True, max_length=50, null=True, verbose_name='所在地域')),
                ('industry', models.CharField(blank=True, max_length=50, null=True, verbose_name='所属行业')),
                ('fullname', models.CharField(blank=True, max_length=100, null=True, verbose_name='股票全称')),
                ('en_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='英文全称')),
                ('list_status', models.CharField(blank=True, choices=[('L', '上市'), ('D', '退市'), ('P', '暂停上市')], max_length=1, null=True, verbose_name='上市状态')),
                ('list_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='上市日期')),
                ('delist_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='退市日期')),
                ('is_hs', models.CharField(blank=True, choices=[('N', '否'), ('H', '沪股通'), ('S', '深股通')], max_length=10, null=True, verbose_name='是否沪深港通标的')),
            ],
            options={
                'verbose_name': '股票代码表',
                'verbose_name_plural': '股票代码表',
                'ordering': ['-last_mod_time'],
                'get_latest_by': 'id',
            },
        ),
    ]
