# Generated by Django 3.0.2 on 2020-05-07 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockmarket', '0002_auto_20200428_2017'),
    ]

    operations = [
        migrations.AddField(
            model_name='stocknamecodemap',
            name='is_marked_jiuzhuan',
            field=models.BooleanField(default=False, verbose_name='是否标注九转'),
        ),
    ]
