# Generated by Django 3.0.2 on 2020-05-25 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockmarket', '0003_stocknamecodemap_is_marked_jiuzhuan'),
    ]

    operations = [
        migrations.AddField(
            model_name='stocknamecodemap',
            name='hist_update_datetime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='更新日期？'),
        ),
        migrations.AddField(
            model_name='stocknamecodemap',
            name='is_hist_downloaded',
            field=models.BooleanField(default=False, verbose_name='交易历史已下载？'),
        ),
        migrations.AddField(
            model_name='stocknamecodemap',
            name='is_hist_updated',
            field=models.BooleanField(default=False, verbose_name='交易历史已更新？'),
        ),
    ]
