# Generated by Django 3.0.2 on 2020-05-25 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockmarket', '0004_auto_20200525_1108'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stocknamecodemap',
            name='hist_update_datetime',
        ),
        migrations.AddField(
            model_name='stocknamecodemap',
            name='hist_update_date',
            field=models.DateField(blank=True, null=True, verbose_name='更新日期？'),
        ),
    ]
