# Generated by Django 3.0.7 on 2020-06-26 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockmarket', '0007_stocknamecodemap_is_marked_wm'),
    ]

    operations = [
        migrations.AddField(
            model_name='stocknamecodemap',
            name='is_marked_tupo',
            field=models.BooleanField(blank=True, null=True, verbose_name='是否标注突破？'),
        ),
    ]
