# Generated by Django 3.0.7 on 2020-06-29 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockmarket', '0008_stocknamecodemap_is_marked_tupo'),
    ]

    operations = [
        migrations.AddField(
            model_name='stocknamecodemap',
            name='is_marked_junxian',
            field=models.BooleanField(blank=True, null=True, verbose_name='是否标注均线买卖点？'),
        ),
    ]
