# Generated by Django 3.0.7 on 2020-11-10 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stockmarket', '0009_stocknamecodemap_is_marked_junxian'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stocknamecodemap',
            name='hist_update_date',
        ),
        migrations.RemoveField(
            model_name='stocknamecodemap',
            name='is_hist_downloaded',
        ),
        migrations.RemoveField(
            model_name='stocknamecodemap',
            name='is_hist_updated',
        ),
        migrations.RemoveField(
            model_name='stocknamecodemap',
            name='is_marked_dingdi',
        ),
        migrations.RemoveField(
            model_name='stocknamecodemap',
            name='is_marked_jiuzhuan',
        ),
        migrations.RemoveField(
            model_name='stocknamecodemap',
            name='is_marked_junxian',
        ),
        migrations.RemoveField(
            model_name='stocknamecodemap',
            name='is_marked_tupo',
        ),
        migrations.RemoveField(
            model_name='stocknamecodemap',
            name='is_marked_wm',
        ),
    ]
