# Generated by Django 3.0.7 on 2020-11-10 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockmarket', '0010_auto_20201110_1641'),
    ]

    operations = [
        migrations.AddField(
            model_name='stocknamecodemap',
            name='last_update_date',
            field=models.DateField(blank=True, null=True, verbose_name='上次更新日期'),
        ),
    ]
