# Generated by Django 3.0.2 on 2020-11-21 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockmarket', '0011_stocknamecodemap_last_update_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='stocknamecodemap',
            name='asset',
            field=models.CharField(blank=True, choices=[('I', 'INDEX'), ('E', 'STOCK')], default='E', max_length=1, null=True, verbose_name='股票/指数'),
        ),
    ]
