# Generated by Django 3.0.2 on 2020-12-26 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockmarket', '0012_stocknamecodemap_asset'),
    ]

    operations = [
        migrations.AddField(
            model_name='stocknamecodemap',
            name='last_analyze_date',
            field=models.DateField(blank=True, null=True, verbose_name='上次分析日期'),
        ),
    ]
