# Generated by Django 3.0.7 on 2021-03-03 13:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('stockmarket', '0014_stocknamecodemap_stock_name_pinyin'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyBasic',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('last_mod_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='最后更新时间')),
                ('stock_code', models.CharField(max_length=50, unique=True, verbose_name='股票代码')),
                ('exchange', models.CharField(blank=True, max_length=10, null=True, verbose_name='交易所代码')),
                ('ts_code', models.CharField(blank=True, max_length=50, verbose_name='TS代码')),
                ('chairman', models.CharField(blank=True, max_length=50, null=True, verbose_name='法人代表')),
                ('manager', models.CharField(blank=True, max_length=50, null=True, verbose_name='总经理')),
                ('secretary', models.CharField(blank=True, max_length=50, null=True, verbose_name='董秘')),
                ('reg_capital', models.FloatField(blank=True, null=True, verbose_name='注册资本')),
                ('setup_date', models.DateField(blank=True, null=True, verbose_name='注册日期')),
                ('province', models.CharField(blank=True, max_length=50, null=True, verbose_name='所在省')),
                ('city', models.CharField(blank=True, max_length=50, null=True, verbose_name='城市')),
                ('introduction', models.CharField(blank=True, max_length=500, null=True, verbose_name='介绍')),
                ('website', models.CharField(blank=True, max_length=128, null=True, verbose_name='主页')),
                ('email', models.CharField(blank=True, max_length=128, null=True, verbose_name='邮件')),
                ('office', models.CharField(blank=True, max_length=100, null=True, verbose_name='办公地址')),
                ('employees', models.IntegerField(blank=True, null=True, verbose_name='员工数')),
                ('main_business', models.CharField(blank=True, max_length=500, null=True, verbose_name='主营业务')),
                ('business_scope', models.CharField(blank=True, max_length=500, null=True, verbose_name='经营范围')),
            ],
            options={
                'verbose_name': '公司基本信息',
                'verbose_name_plural': '公司基本信息',
                'ordering': ['-last_mod_time'],
                'get_latest_by': 'id',
            },
        ),
        migrations.CreateModel(
            name='CompanyManagers',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('last_mod_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='最后更新时间')),
                ('stock_code', models.CharField(max_length=50, unique=True, verbose_name='股票代码')),
                ('ts_code', models.CharField(blank=True, max_length=50, verbose_name='TS代码')),
                ('announce_date', models.DateField(blank=True, null=True, verbose_name='公告日期')),
                ('name', models.CharField(blank=True, max_length=50, null=True, verbose_name='姓名')),
                ('gender', models.CharField(blank=True, max_length=10, null=True, verbose_name='性别')),
                ('level', models.CharField(blank=True, max_length=50, null=True, verbose_name='岗位类别')),
                ('title', models.CharField(blank=True, max_length=10, null=True, verbose_name='岗位')),
                ('edu', models.CharField(blank=True, max_length=10, null=True, verbose_name='学历')),
                ('national', models.CharField(blank=True, max_length=10, null=True, verbose_name='国籍')),
                ('birthday', models.CharField(blank=True, max_length=10, null=True, verbose_name='出生年月')),
                ('begin_date', models.DateField(blank=True, null=True, verbose_name='上任日期')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='离任日期')),
                ('resume', models.CharField(blank=True, max_length=500, null=True, verbose_name='简历')),
            ],
            options={
                'verbose_name': '公司管理层',
                'verbose_name_plural': '公司管理层',
                'ordering': ['-last_mod_time'],
                'get_latest_by': 'id',
            },
        ),
        migrations.CreateModel(
            name='ManagerRewards',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('last_mod_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='最后更新时间')),
                ('stock_code', models.CharField(max_length=50, unique=True, verbose_name='股票代码')),
                ('ts_code', models.CharField(blank=True, max_length=50, verbose_name='TS代码')),
                ('announce_date', models.DateField(blank=True, null=True, verbose_name='公告日期')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='截至日期')),
                ('name', models.CharField(blank=True, max_length=50, null=True, verbose_name='姓名')),
                ('title', models.DateField(blank=True, max_length=50, null=True, verbose_name='职务')),
                ('reward', models.FloatField(blank=True, null=True, verbose_name='报酬')),
                ('hold_value', models.FloatField(blank=True, null=True, verbose_name='持股数')),
            ],
            options={
                'verbose_name': '管理层薪酬',
                'verbose_name_plural': '管理层薪酬',
                'ordering': ['-last_mod_time'],
                'get_latest_by': 'id',
            },
        ),
    ]
