# Generated by Django 3.0.7 on 2021-03-05 13:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('stockmarket', '0015_companybasic_companymanagers_managerrewards'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyDailyBasic',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('last_mod_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='最后更新时间')),
                ('ts_code', models.CharField(blank=True, max_length=50, unique=True, verbose_name='TS代码')),
                ('stock_code', models.CharField(max_length=50, unique=True, verbose_name='股票代码')),
                ('trade_date', models.DateField(blank=True, null=True, verbose_name='交易日期')),
                ('close', models.FloatField(blank=True, null=True, verbose_name='收盘价')),
                ('turnover_rate', models.FloatField(blank=True, max_length=50, null=True, verbose_name='换手率')),
                ('turnover_rate_f', models.FloatField(blank=True, max_length=50, null=True, verbose_name='换手率(自由流通)')),
                ('volume_ratio', models.FloatField(blank=True, null=True, verbose_name='量比')),
                ('pe', models.FloatField(blank=True, null=True, verbose_name='市盈率')),
                ('pe_ttm', models.FloatField(blank=True, null=True, verbose_name='市盈率TTM')),
                ('dv_ratio', models.FloatField(blank=True, null=True, verbose_name='股息')),
                ('dv_ttm', models.FloatField(blank=True, null=True, verbose_name='股息率TTM')),
                ('total_share', models.FloatField(blank=True, null=True, verbose_name='总股本')),
                ('float_share', models.FloatField(blank=True, null=True, verbose_name='流通股本')),
                ('free_share', models.FloatField(blank=True, null=True, verbose_name='自由流通股本')),
                ('total_mv', models.FloatField(blank=True, null=True, verbose_name='总市值')),
                ('circ_mv', models.FloatField(blank=True, null=True, verbose_name='流通市值')),
            ],
            options={
                'verbose_name': '公司每日基本',
                'verbose_name_plural': '公司每日基本',
                'ordering': ['-last_mod_time'],
                'get_latest_by': 'id',
            },
        ),
        migrations.AlterField(
            model_name='companybasic',
            name='ts_code',
            field=models.CharField(blank=True, max_length=50, unique=True, verbose_name='TS代码'),
        ),
    ]
