# Generated by Django 3.0.7 on 2021-03-07 10:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stockmarket', '0016_auto_20210305_2113'),
    ]

    operations = [
        migrations.AddField(
            model_name='companybasic',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='stockmarket.StockNameCodeMap'),
        ),
        migrations.AddField(
            model_name='companydailybasic',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='stockmarket.StockNameCodeMap'),
        ),
        migrations.AddField(
            model_name='companymanagers',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='stockmarket.StockNameCodeMap'),
        ),
        migrations.AddField(
            model_name='managerrewards',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='stockmarket.StockNameCodeMap'),
        ),
    ]
