# Generated by Django 3.0.7 on 2021-03-09 23:13

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('stockmarket', '0017_auto_20210307_1803'),
    ]

    operations = [
        migrations.AddField(
            model_name='companydailybasic',
            name='pb',
            field=models.FloatField(blank=True, null=True, verbose_name='市净率'),
        ),
        migrations.AddField(
            model_name='companydailybasic',
            name='ps',
            field=models.FloatField(blank=True, null=True, verbose_name='市销率'),
        ),
        migrations.AddField(
            model_name='companydailybasic',
            name='ps_ttm',
            field=models.FloatField(blank=True, null=True, verbose_name='市销率TTM'),
        ),
        migrations.CreateModel(
            name='IndexDailyBasic',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('last_mod_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='最后更新时间')),
                ('ts_code', models.CharField(blank=True, max_length=50, unique=True, verbose_name='TS代码')),
                ('trade_date', models.DateField(blank=True, null=True, verbose_name='交易日期')),
                ('turnover_rate', models.FloatField(blank=True, max_length=50, null=True, verbose_name='换手率')),
                ('turnover_rate_f', models.FloatField(blank=True, max_length=50, null=True, verbose_name='换手率(自由流通)')),
                ('pe', models.FloatField(blank=True, null=True, verbose_name='市盈率')),
                ('pe_ttm', models.FloatField(blank=True, null=True, verbose_name='市盈率TTM')),
                ('pb', models.FloatField(blank=True, null=True, verbose_name='市净率')),
                ('total_share', models.FloatField(blank=True, null=True, verbose_name='总股本')),
                ('float_share', models.FloatField(blank=True, null=True, verbose_name='流通股本')),
                ('free_share', models.FloatField(blank=True, null=True, verbose_name='自由流通股本')),
                ('total_mv', models.FloatField(blank=True, null=True, verbose_name='总市值')),
                ('float_mv', models.FloatField(blank=True, null=True, verbose_name='流通市值')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='stockmarket.StockNameCodeMap')),
            ],
            options={
                'verbose_name': '指数每日基本',
                'verbose_name_plural': '指数每日基本',
                'ordering': ['-last_mod_time'],
                'get_latest_by': 'id',
            },
        ),
    ]
