# Generated by Django 3.0.7 on 2021-03-09 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockmarket', '0018_auto_20210310_0713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companydailybasic',
            name='stock_code',
            field=models.CharField(max_length=50, verbose_name='股票代码'),
        ),
        migrations.AlterField(
            model_name='companymanagers',
            name='ts_code',
            field=models.CharField(blank=True, max_length=50, unique=True, verbose_name='TS代码'),
        ),
        migrations.AlterField(
            model_name='indexdailybasic',
            name='ts_code',
            field=models.CharField(blank=True, max_length=50, verbose_name='TS代码'),
        ),
    ]
