# Generated by Django 3.0.7 on 2021-03-09 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockmarket', '0019_auto_20210310_0720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companydailybasic',
            name='ts_code',
            field=models.CharField(blank=True, max_length=50, verbose_name='TS代码'),
        ),
    ]
