# Generated by Django 3.0.7 on 2021-03-13 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockmarket', '0020_auto_20210310_0725'),
    ]

    operations = [
        migrations.AddField(
            model_name='companybasic',
            name='index_category',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='板块'),
        ),
        migrations.AlterField(
            model_name='companymanagers',
            name='stock_code',
            field=models.CharField(max_length=50, verbose_name='股票代码'),
        ),
        migrations.AlterField(
            model_name='companymanagers',
            name='ts_code',
            field=models.CharField(blank=True, max_length=50, verbose_name='TS代码'),
        ),
        migrations.AlterField(
            model_name='managerrewards',
            name='stock_code',
            field=models.CharField(max_length=50, verbose_name='股票代码'),
        ),
    ]
