# Generated by Django 3.0.7 on 2021-03-13 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockmarket', '0022_auto_20210313_0925'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companymanagers',
            name='stock_code',
        ),
        migrations.RemoveField(
            model_name='managerrewards',
            name='stock_code',
        ),
        migrations.AlterField(
            model_name='companymanagers',
            name='national',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='国籍'),
        ),
        migrations.AlterField(
            model_name='companymanagers',
            name='title',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='岗位'),
        ),
    ]
