# Generated by Django 3.0.7 on 2021-03-13 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockmarket', '0023_auto_20210313_1519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='managerrewards',
            name='title',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='职务'),
        ),
    ]
