# Generated by Django 3.0.7 on 2021-03-27 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockmarket', '0025_auto_20210320_1549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stocknamecodemap',
            name='stock_code',
            field=models.CharField(max_length=50, verbose_name='股票代码'),
        ),
        migrations.AlterField(
            model_name='stocknamecodemap',
            name='stock_name',
            field=models.CharField(max_length=50, verbose_name='股票名称'),
        ),
        migrations.AlterField(
            model_name='stocknamecodemap',
            name='ts_code',
            field=models.CharField(blank=True, max_length=50, unique=True, verbose_name='TS代码'),
        ),
    ]
