# Generated by Django 3.0.2 on 2021-09-19 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockmarket', '0027_auto_20210902_2023'),
    ]

    operations = [
        migrations.AddField(
            model_name='stocknamecodemap',
            name='dailybasic_date',
            field=models.DateField(blank=True, null=True, verbose_name='基本面下载日期'),
        ),
    ]
