# Generated by Django 3.0.2 on 2021-09-19 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockmarket', '0028_stocknamecodemap_dailybasic_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companydailybasic',
            name='ts_code',
            field=models.CharField(blank=True, db_index=True, max_length=50, verbose_name='TS代码'),
        ),
        migrations.AlterUniqueTogether(
            name='companydailybasic',
            unique_together={('ts_code', 'trade_date')},
        ),
    ]
