# Generated by Django 3.0.2 on 2021-10-21 04:12

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('stockmarket', '0030_companydailybasicext_industry'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='companydailybasic',
            options={'get_latest_by': 'id', 'ordering': ['-trade_date'], 'verbose_name': '公司每日基本面', 'verbose_name_plural': '公司每日基本面'},
        ),
        migrations.AlterModelOptions(
            name='companymanagers',
            options={'get_latest_by': 'id', 'ordering': ['-announce_date'], 'verbose_name': '公司管理层', 'verbose_name_plural': '公司管理层'},
        ),
        migrations.AlterModelOptions(
            name='stocknamecodemap',
            options={'get_latest_by': 'id', 'ordering': ['-last_mod_time'], 'verbose_name': '股票基本信息', 'verbose_name_plural': '股票基本信息'},
        ),
        migrations.AddField(
            model_name='industry',
            name='created_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间'),
        ),
        migrations.AddField(
            model_name='industry',
            name='industry_pinyin',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='行业名称拼音'),
        ),
        migrations.AddField(
            model_name='industry',
            name='last_mod_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='最后更新时间'),
        ),
        migrations.AddField(
            model_name='stocknamecodemap',
            name='ind',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ind', to='stockmarket.Industry'),
        ),
        migrations.AlterField(
            model_name='companybasic',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='company_basic', to='stockmarket.StockNameCodeMap'),
        ),
        migrations.AlterField(
            model_name='companydailybasic',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='daily_basic', to='stockmarket.StockNameCodeMap'),
        ),
        migrations.AlterField(
            model_name='companymanagers',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manager', to='stockmarket.StockNameCodeMap'),
        ),
        migrations.AlterField(
            model_name='indexdailybasic',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='index_basic', to='stockmarket.StockNameCodeMap'),
        ),
        migrations.AlterField(
            model_name='industry',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='industry',
            name='pb_10pct',
            field=models.FloatField(blank=True, null=True, verbose_name='PB低位'),
        ),
        migrations.AlterField(
            model_name='industry',
            name='pb_50pct',
            field=models.FloatField(blank=True, null=True, verbose_name='PB中位'),
        ),
        migrations.AlterField(
            model_name='industry',
            name='pb_90pct',
            field=models.FloatField(blank=True, null=True, verbose_name='PB高位'),
        ),
        migrations.AlterField(
            model_name='industry',
            name='pe_10pct',
            field=models.FloatField(blank=True, null=True, verbose_name='PE低位'),
        ),
        migrations.AlterField(
            model_name='industry',
            name='pe_50pct',
            field=models.FloatField(blank=True, null=True, verbose_name='PE中位'),
        ),
        migrations.AlterField(
            model_name='industry',
            name='pe_90pct',
            field=models.FloatField(blank=True, null=True, verbose_name='PE高位'),
        ),
        migrations.AlterField(
            model_name='industry',
            name='ps_10pct',
            field=models.FloatField(blank=True, null=True, verbose_name='PS低位'),
        ),
        migrations.AlterField(
            model_name='industry',
            name='ps_50pct',
            field=models.FloatField(blank=True, null=True, verbose_name='PS中位'),
        ),
        migrations.AlterField(
            model_name='industry',
            name='ps_90pct',
            field=models.FloatField(blank=True, null=True, verbose_name='PS高位'),
        ),
        migrations.AlterField(
            model_name='industry',
            name='snap_date',
            field=models.DateField(blank=True, null=True, verbose_name='统计日期'),
        ),
        migrations.AlterField(
            model_name='industry',
            name='stock_count',
            field=models.IntegerField(blank=True, null=True, verbose_name='股票数'),
        ),
    ]
