# Generated by Django 3.0.2 on 2021-10-21 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockmarket', '0031_auto_20211021_1212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='industry',
            name='industry',
            field=models.CharField(db_index=True, max_length=50, unique=True, verbose_name='行业'),
        ),
    ]
