# Generated by Django 3.0.2 on 2021-10-30 06:12

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('stockmarket', '0032_auto_20211021_1312'),
    ]

    operations = [
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('last_mod_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='最后更新时间')),
                ('name', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='省份')),
                ('country', models.CharField(blank=True, default='中国', max_length=50, verbose_name='国家')),
            ],
            options={
                'verbose_name': '省份',
                'verbose_name_plural': '省份',
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='stocknamecodemap',
            name='ind',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='company_ind', to='stockmarket.Industry'),
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('last_mod_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='最后更新时间')),
                ('name', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='城市')),
                ('province', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='city_province', to='stockmarket.Province')),
            ],
            options={
                'verbose_name': '城市',
                'verbose_name_plural': '城市',
                'ordering': ['name'],
            },
        ),
    ]
