# Generated by Django 3.0.2 on 2021-11-28 03:31

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('stockmarket', '0037_companybasicfilter'),
    ]

    operations = [
        migrations.AddField(
            model_name='companydailybasicext',
            name='float_hold_pct',
            field=models.FloatField(blank=True, null=True, verbose_name='流通股持仓%'),
        ),
        migrations.CreateModel(
            name='CompanyTop10FloatHolders',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('last_mod_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='最后更新时间')),
                ('ts_code', models.CharField(blank=True, max_length=50, verbose_name='TS代码')),
                ('announce_date', models.DateField(blank=True, null=True, verbose_name='公告日期')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='截至日期')),
                ('holder_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='股东名称')),
                ('hold_amount', models.FloatField(blank=True, null=True, verbose_name='持股数')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='top10_holder', to='stockmarket.StockNameCodeMap')),
            ],
            options={
                'verbose_name': '前10大流通股',
                'verbose_name_plural': '前10大流通股',
                'ordering': ['-end_date'],
                'get_latest_by': 'id',
            },
        ),
        migrations.CreateModel(
            name='CompanyIncomeSheet',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('last_mod_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='最后更新时间')),
                ('ts_code', models.CharField(blank=True, max_length=50, verbose_name='TS代码')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='income', to='stockmarket.StockNameCodeMap')),
            ],
            options={
                'verbose_name': '企业营收表',
                'verbose_name_plural': '企业营收表',
                'ordering': ['ts_code'],
                'get_latest_by': 'id',
            },
        ),
        migrations.CreateModel(
            name='CompanyCashflow',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('last_mod_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='最后更新时间')),
                ('ts_code', models.CharField(blank=True, max_length=50, verbose_name='TS代码')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cashflow', to='stockmarket.StockNameCodeMap')),
            ],
            options={
                'verbose_name': '现金流量表',
                'verbose_name_plural': '现金流量表',
                'ordering': ['ts_code'],
                'get_latest_by': 'id',
            },
        ),
        migrations.CreateModel(
            name='CompanyBalanceSheet',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('last_mod_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='最后更新时间')),
                ('ts_code', models.CharField(blank=True, max_length=50, verbose_name='TS代码')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='balance_sheet', to='stockmarket.StockNameCodeMap')),
            ],
            options={
                'verbose_name': '资产负债表',
                'verbose_name_plural': '资产负债表',
                'ordering': ['ts_code'],
                'get_latest_by': 'id',
            },
        ),
    ]
