# Generated by Django 3.0.2 on 2021-11-28 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockmarket', '0038_auto_20211128_1131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companytop10floatholders',
            name='holder_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='股东名称'),
        ),
    ]
