# Generated by Django 3.0.2 on 2021-11-29 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockmarket', '0039_auto_20211128_1806'),
    ]

    operations = [
        migrations.AddField(
            model_name='stocknamecodemap',
            name='top10_holder_date',
            field=models.DateField(blank=True, null=True, verbose_name='流通股持仓下载日期'),
        ),
    ]
