# Generated by Django 3.0.2 on 2021-11-30 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockmarket', '0040_stocknamecodemap_top10_holder_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companytop10floatholders',
            name='ts_code',
            field=models.CharField(blank=True, db_index=True, max_length=50, verbose_name='TS代码'),
        ),
    ]
