# Generated by Django 3.0.2 on 2021-12-01 13:57

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('stockmarket', '0041_auto_20211130_2200'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyTop10FloatHoldersFilter',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('last_mod_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='最后更新时间')),
                ('ts_code', models.CharField(blank=True, db_index=True, max_length=50, verbose_name='TS代码')),
                ('announce_date', models.DateField(blank=True, null=True, verbose_name='公告日期')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='截至日期')),
                ('hold_pct', models.FloatField(blank=True, null=True, verbose_name='持股比例')),
                ('hold_amount', models.FloatField(blank=True, null=True, verbose_name='持股数')),
                ('float_amount', models.FloatField(blank=True, null=True, verbose_name='流通股数')),
                ('company', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='top10_holder_pct', to='stockmarket.StockNameCodeMap')),
            ],
            options={
                'verbose_name': '前10大流通股持股比例',
                'verbose_name_plural': '前10大流通股持股比例',
                'ordering': ['-end_date'],
                'get_latest_by': 'id',
            },
        ),
    ]
