# Generated by Django 3.0.2 on 2021-12-05 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockmarket', '0043_companytop10floatholdersstat'),
    ]

    operations = [
        migrations.AddField(
            model_name='companytop10floatholdersstat',
            name='close',
            field=models.FloatField(blank=True, null=True, verbose_name='收盘价'),
        ),
        migrations.AddField(
            model_name='companytop10floatholdersstat',
            name='pb',
            field=models.FloatField(blank=True, null=True, verbose_name='市净率'),
        ),
        migrations.AddField(
            model_name='companytop10floatholdersstat',
            name='pe',
            field=models.FloatField(blank=True, null=True, verbose_name='市盈率'),
        ),
        migrations.AddField(
            model_name='companytop10floatholdersstat',
            name='pe_ttm',
            field=models.FloatField(blank=True, null=True, verbose_name='市盈率TTM'),
        ),
        migrations.AddField(
            model_name='companytop10floatholdersstat',
            name='ps',
            field=models.FloatField(blank=True, null=True, verbose_name='市销率'),
        ),
        migrations.AddField(
            model_name='companytop10floatholdersstat',
            name='ps_ttm',
            field=models.FloatField(blank=True, null=True, verbose_name='市销率TTM'),
        ),
    ]
