# Generated by Django 3.2.10 on 2022-01-10 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockmarket', '0045_auto_20211230_2053'),
    ]

    operations = [
        migrations.AddField(
            model_name='companybalancesheet',
            name='acc_exp',
            field=models.FloatField(blank=True, null=True, verbose_name='预提费用'),
        ),
        migrations.AddField(
            model_name='companybalancesheet',
            name='acc_receivable',
            field=models.FloatField(blank=True, null=True, verbose_name='应收款项'),
        ),
        migrations.AddField(
            model_name='companybalancesheet',
            name='accounts_pay',
            field=models.FloatField(blank=True, null=True, verbose_name='应付票据及应付账款'),
        ),
        migrations.AddField(
            model_name='companybalancesheet',
            name='accounts_receiv',
            field=models.FloatField(blank=True, null=True, verbose_name='应收账款'),
        ),
        migrations.AddField(
            model_name='companybalancesheet',
            name='accounts_receiv_bill',
            field=models.FloatField(blank=True, null=True, verbose_name='应收票据及应收账款'),
        ),
        migrations.AddField(
            model_name='companybalancesheet',
            name='acct_payable',
            field=models.FloatField(blank=True, null=True, verbose_name='应付账款'),
        ),
        migrations.AddField(
            model_name='companybalancesheet',
            name='acting_trading_sec',
            field=models.FloatField(blank=True, null=True, verbose_name='代理买卖证券款'),
        ),
        migrations.AddField(
            model_name='companybalancesheet',
            name='acting_uw_sec',
            field=models.FloatField(blank=True, null=True, verbose_name='代理承销证券款'),
        ),
        migrations.AddField(
            model_name='companybalancesheet',
            name='adv_receipts',
            field=models.FloatField(blank=True, null=True, verbose_name='预收款项'),
        ),
        migrations.AddField(
            model_name='companybalancesheet',
            name='agency_bus_liab',
            field=models.FloatField(blank=True, null=True, verbose_name='代理业务负债'),
        ),
        migrations.AddField(
            model_name='companybalancesheet',
            name='amor_exp',
            field=models.FloatField(blank=True, null=True, verbose_name='长期待摊费用'),
        ),
        migrations.AddField(
            model_name='companybalancesheet',
            name='announce_date',
            field=models.DateField(blank=True, null=True, verbose_name='公告日期'),
        ),
        migrations.AddField(
            model_name='companybalancesheet',
            name='bond_payable',
            field=models.FloatField(blank=True, null=True, verbose_name='应付债券'),
        ),
        migrations.AddField(
            model_name='companybalancesheet',
            name='cap_rese',
            field=models.FloatField(blank=True, null=True, verbose_name='资本公积金'),
        ),
        migrations.AddField(
            model_name='companybalancesheet',
            name='cash_reser_cb',
            field=models.FloatField(blank=True, null=True, verbose_name='现金及存放中央银行款项'),
        ),
        migrations.AddField(
            model_name='companybalancesheet',
            name='cb_borr',
            field=models.FloatField(blank=True, null=True, verbose_name='向中央银行借款'),
        ),
        migrations.AddField(
            model_name='companybalancesheet',
            name='cip',
            field=models.FloatField(blank=True, null=True, verbose_name='在建工程'),
        ),
        migrations.AddField(
            model_name='companybalancesheet',
            name='cip_total',
            field=models.FloatField(blank=True, null=True, verbose_name='在建工程'),
        ),
        migrations.AddField(
            model_name='companybalancesheet',
            name='client_depos',
            field=models.FloatField(blank=True, null=True, verbose_name='客户资金存款'),
        ),
        migrations.AddField(
            model_name='companybalancesheet',
            name='client_prov',
            field=models.FloatField(blank=True, null=True, verbose_name='客户备付金'),
        ),
        migrations.AddField(
            model_name='companybalancesheet',
            name='comm_payable',
            field=models.FloatField(blank=True, null=True, verbose_name='应付手续费及佣金'),
        ),
        migrations.AddField(
            model_name='companybalancesheet',
            name='comp_type',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='公司类型'),
        ),
        migrations.AddField(
            model_name='companybalancesheet',
            name='const_materials',
            field=models.FloatField(blank=True, null=True, verbose_name='工程物资'),
        ),
        migrations.AddField(
            model_name='companybalancesheet',
            name='contract_assets',
            field=models.FloatField(blank=True, null=True, verbose_name='合同资产'),
        ),
        migrations.AddField(
            model_name='companybalancesheet',
            name='contract_liab',
            field=models.FloatField(blank=True, null=True, verbose_name='合同负债'),
        ),
        migrations.AddField(
            model_name='companybalancesheet',
            name='cost_fin_assets',
            field=models.FloatField(blank=True, null=True, verbose_name='以摊余成本计量的金融资产'),
        ),
        migrations.AddField(
            model_name='companybalancesheet',
            name='debt_invest',
            field=models.FloatField(blank=True, null=True, verbose_name='债权投资'),
        ),
        migrations.AddField(
            model_name='companybalancesheet',
            name='decr_in_disbur',
            field=models.FloatField(blank=True, null=True, verbose_name='发放贷款及垫款'),
        ),
        migrations.AddField(
            model_name='companybalancesheet',
            name='defer_inc_non_cur_liab',
            field=models.FloatField(blank=True, null=True, verbose_name='递延收益-非流动负债'),
        ),
        migrations.AddField(
            model_name='companybalancesheet',
            name='defer_tax_assets',
            field=models.FloatField(blank=True, null=True, verbose_name='递延所得税资产'),
        ),
        migrations.AddField(
            model_name='companybalancesheet',
            name='defer_tax_liab',
            field=models.FloatField(blank=True, null=True, verbose_name='递延所得税负债'),
        ),
        migrations.AddField(
            model_name='companybalancesheet',
            name='deferred_inc',
            field=models.FloatField(blank=True, null=True, verbose_name='递延收益'),
        ),
        migrations.AddField(
            model_name='companybalancesheet',
            name='depos',
            field=models.FloatField(blank=True, null=True, verbose_name='吸收存款'),
        ),
        migrations.AddField(
            model_name='companybalancesheet',
            name='depos_ib_deposits',
            field=models.FloatField(blank=True, null=True, verbose_name='吸收存款及同业存放'),
        ),
        migrations.AddField(
            model_name='companybalancesheet',
            name='depos_in_oth_bfi',
            field=models.FloatField(blank=True, null=True, verbose_name='存放同业和其它金融机构款项'),
        ),
        migrations.AddField(
            model_name='companybalancesheet',
            name='depos_oth_bfi',
            field=models.FloatField(blank=True, null=True, verbose_name='同业和其它金融机构存放款项'),
        ),
        migrations.AddField(
            model_name='companybalancesheet',
            name='depos_received',
            field=models.FloatField(blank=True, null=True, verbose_name='存入保证金'),
        ),
        migrations.AddField(
            model_name='companybalancesheet',
            name='deriv_assets',
            field=models.FloatField(blank=True, null=True, verbose_name='衍生金融资产'),
        ),
        migrations.AddField(
            model_name='companybalancesheet',
            name='deriv_liab',
            field=models.FloatField(blank=True, null=True, verbose_name='衍生金融负债'),
        ),
        migrations.AddField(
            model_name='companybalancesheet',
            name='div_payable',
            field=models.FloatField(blank=True, null=True, verbose_name='应付股利'),
        ),
        migrations.AddField(
            model_name='companybalancesheet',
            name='div_receiv',
            field=models.FloatField(blank=True, null=True, verbose_name='应收股利'),
        ),
        migrations.AddField(
            model_name='companybalancesheet',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='报告期'),
        ),
        migrations.AddField(
            model_name='companybalancesheet',
            name='end_type',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='报告期类型'),
        ),
        migrations.AddField(
            model_name='companybalancesheet',
            name='estimated_liab',
            field=models.FloatField(blank=True, null=True, verbose_name='预计负债'),
        ),
        migrations.AddField(
            model_name='companybalancesheet',
            name='f_announce_date',
            field=models.DateField(blank=True, null=True, verbose_name='实际公告日期'),
        ),
        migrations.AddField(
            model_name='companybalancesheet',
            name='fa_avail_for_sale',
            field=models.FloatField(blank=True, null=True, verbose_name='可供出售金融资产'),
        ),
        migrations.AddField(
            model_name='companybalancesheet',
            name='fair_value_fin_assets',
            field=models.FloatField(blank=True, null=True, verbose_name='公允价值计量计入的金融资产'),
        ),
        migrations.AddField(
            model_name='companybalancesheet',
            name='fix_assets',
            field=models.FloatField(blank=True, null=True, verbose_name='固定资产'),
        ),
        migrations.AddField(
            model_name='companybalancesheet',
            name='fix_assets_total',
            field=models.FloatField(blank=True, null=True, verbose_name='固定资产(合计)'),
        ),
        migrations.AddField(
            model_name='companybalancesheet',
            name='fixed_assets_disp',
            field=models.FloatField(blank=True, null=True, verbose_name='固定资产清理'),
        ),
        migrations.AddField(
            model_name='companybalancesheet',
            name='forex_differ',
            field=models.FloatField(blank=True, null=True, verbose_name='外币报表折算差额'),
        ),
        migrations.AddField(
            model_name='companybalancesheet',
            name='goodwill',
            field=models.FloatField(blank=True, null=True, verbose_name='商誉'),
        ),
        migrations.AddField(
            model_name='companybalancesheet',
            name='hfs_assets',
            field=models.FloatField(blank=True, null=True, verbose_name='持有待售的资产'),
        ),
        migrations.AddField(
            model_name='companybalancesheet',
            name='hfs_sales',
            field=models.FloatField(blank=True, null=True, verbose_name='持有待售的负债'),
        ),
        migrations.AddField(
            model_name='companybalancesheet',
            name='htm_invest',
            field=models.FloatField(blank=True, null=True, verbose_name='持有至到期投资'),
        ),
        migrations.AddField(
            model_name='companybalancesheet',
            name='indem_payable',
            field=models.FloatField(blank=True, null=True, verbose_name='应付赔付款'),
        ),
        migrations.AddField(
            model_name='companybalancesheet',
            name='indep_acct_assets',
            field=models.FloatField(blank=True, null=True, verbose_name='独立账户资产'),
        ),
        migrations.AddField(
            model_name='companybalancesheet',
            name='indept_acc_liab',
            field=models.FloatField(blank=True, null=True, verbose_name='独立账户负债'),
        ),
        migrations.AddField(
            model_name='companybalancesheet',
            name='int_payable',
            field=models.FloatField(blank=True, null=True, verbose_name='应付利息'),
        ),
        migrations.AddField(
            model_name='companybalancesheet',
            name='int_receiv',
            field=models.FloatField(blank=True, null=True, verbose_name='应收利息'),
        ),
        migrations.AddField(
            model_name='companybalancesheet',
            name='intan_assets',
            field=models.FloatField(blank=True, null=True, verbose_name='无形资产'),
        ),
        migrations.AddField(
            model_name='companybalancesheet',
            name='inventories',
            field=models.FloatField(blank=True, null=True, verbose_name='存货'),
        ),
        migrations.AddField(
            model_name='companybalancesheet',
            name='invest_as_receiv',
            field=models.FloatField(blank=True, null=True, verbose_name='应收款项类投资'),
        ),
        migrations.AddField(
            model_name='companybalancesheet',
            name='invest_loss_unconf',
            field=models.FloatField(blank=True, null=True, verbose_name='未确认的投资损失'),
        ),
        migrations.AddField(
            model_name='companybalancesheet',
            name='invest_real_estate',
            field=models.FloatField(blank=True, null=True, verbose_name='投资性房地产'),
        ),
        migrations.AddField(
            model_name='companybalancesheet',
            name='lease_liab',
            field=models.FloatField(blank=True, null=True, verbose_name='租赁负债'),
        ),
        migrations.AddField(
            model_name='companybalancesheet',
            name='lending_funds',
            field=models.FloatField(blank=True, null=True, verbose_name='融出资金'),
        ),
        migrations.AddField(
            model_name='companybalancesheet',
            name='loan_oth_bank',
            field=models.FloatField(blank=True, null=True, verbose_name='拆入资金'),
        ),
        migrations.AddField(
            model_name='companybalancesheet',
            name='loanto_oth_bank_fi',
            field=models.FloatField(blank=True, null=True, verbose_name='拆出资金'),
        ),
        migrations.AddField(
            model_name='companybalancesheet',
            name='long_pay_total',
            field=models.FloatField(blank=True, null=True, verbose_name='长期应付款'),
        ),
        migrations.AddField(
            model_name='companybalancesheet',
            name='lt_amor_exp',
            field=models.FloatField(blank=True, null=True, verbose_name='长期待摊费用'),
        ),
        migrations.AddField(
            model_name='companybalancesheet',
            name='lt_borr',
            field=models.FloatField(blank=True, null=True, verbose_name='长期借款'),
        ),
        migrations.AddField(
            model_name='companybalancesheet',
            name='lt_eqt_invest',
            field=models.FloatField(blank=True, null=True, verbose_name='长期股权投资'),
        ),
        migrations.AddField(
            model_name='companybalancesheet',
            name='lt_payable',
            field=models.FloatField(blank=True, null=True, verbose_name='长期应付款'),
        ),
        migrations.AddField(
            model_name='companybalancesheet',
            name='lt_payroll_payable',
            field=models.FloatField(blank=True, null=True, verbose_name='长期应付职工薪酬'),
        ),
        migrations.AddField(
            model_name='companybalancesheet',
            name='lt_rec',
            field=models.FloatField(blank=True, null=True, verbose_name='长期应收款'),
        ),
        migrations.AddField(
            model_name='companybalancesheet',
            name='minority_int',
            field=models.FloatField(blank=True, null=True, verbose_name='少数股东权益'),
        ),
        migrations.AddField(
            model_name='companybalancesheet',
            name='money_cap',
            field=models.FloatField(blank=True, null=True, verbose_name='货币资金'),
        ),
        migrations.AddField(
            model_name='companybalancesheet',
            name='nca_within_1y',
            field=models.FloatField(blank=True, null=True, verbose_name='一年内到期的非流动资产'),
        ),
        migrations.AddField(
            model_name='companybalancesheet',
            name='non_cur_liab_due_1y',
            field=models.FloatField(blank=True, null=True, verbose_name='一年内到期的非流动负债'),
        ),
        migrations.AddField(
            model_name='companybalancesheet',
            name='notes_payable',
            field=models.FloatField(blank=True, null=True, verbose_name='应付票据'),
        ),
        migrations.AddField(
            model_name='companybalancesheet',
            name='notes_receiv',
            field=models.FloatField(blank=True, null=True, verbose_name='应收票据'),
        ),
        migrations.AddField(
            model_name='companybalancesheet',
            name='oil_and_gas_assets',
            field=models.FloatField(blank=True, null=True, verbose_name='油气资产'),
        ),
        migrations.AddField(
            model_name='companybalancesheet',
            name='ordin_risk_reser',
            field=models.FloatField(blank=True, null=True, verbose_name='一般风险准备'),
        ),
        migrations.AddField(
            model_name='companybalancesheet',
            name='oth_assets',
            field=models.FloatField(blank=True, null=True, verbose_name='其他资产'),
        ),
        migrations.AddField(
            model_name='companybalancesheet',
            name='oth_comp_income',
            field=models.FloatField(blank=True, null=True, verbose_name='其他综合收益'),
        ),
        migrations.AddField(
            model_name='companybalancesheet',
            name='oth_cur_assets',
            field=models.FloatField(blank=True, null=True, verbose_name='其他流动资产'),
        ),
        migrations.AddField(
            model_name='companybalancesheet',
            name='oth_cur_liab',
            field=models.FloatField(blank=True, null=True, verbose_name='其他流动负债'),
        ),
        migrations.AddField(
            model_name='companybalancesheet',
            name='oth_debt_invest',
            field=models.FloatField(blank=True, null=True, verbose_name='其他债权投资'),
        ),
        migrations.AddField(
            model_name='companybalancesheet',
            name='oth_eq_invest',
            field=models.FloatField(blank=True, null=True, verbose_name='其他权益工具投资'),
        ),
        migrations.AddField(
            model_name='companybalancesheet',
            name='oth_eq_ppbond',
            field=models.FloatField(blank=True, null=True, verbose_name='其他权益工具永续债'),
        ),
        migrations.AddField(
            model_name='companybalancesheet',
            name='oth_eqt_tools',
            field=models.FloatField(blank=True, null=True, verbose_name='其他权益工具'),
        ),
        migrations.AddField(
            model_name='companybalancesheet',
            name='oth_eqt_tools_p_shr',
            field=models.FloatField(blank=True, null=True, verbose_name='其他权益工具(优先股)'),
        ),
        migrations.AddField(
            model_name='companybalancesheet',
            name='oth_illiq_fin_assets',
            field=models.FloatField(blank=True, null=True, verbose_name='其他非流动金融资产'),
        ),
        migrations.AddField(
            model_name='companybalancesheet',
            name='oth_liab',
            field=models.FloatField(blank=True, null=True, verbose_name='其他负债'),
        ),
        migrations.AddField(
            model_name='companybalancesheet',
            name='oth_nca',
            field=models.FloatField(blank=True, null=True, verbose_name='其他非流动资产'),
        ),
        migrations.AddField(
            model_name='companybalancesheet',
            name='oth_ncl',
            field=models.FloatField(blank=True, null=True, verbose_name='其他非流动负债'),
        ),
        migrations.AddField(
            model_name='companybalancesheet',
            name='oth_pay_total',
            field=models.FloatField(blank=True, null=True, verbose_name='在建工程'),
        ),
        migrations.AddField(
            model_name='companybalancesheet',
            name='oth_payable',
            field=models.FloatField(blank=True, null=True, verbose_name='其他应付款'),
        ),
        migrations.AddField(
            model_name='companybalancesheet',
            name='oth_rcv_total',
            field=models.FloatField(blank=True, null=True, verbose_name='其他应收款(合计)'),
        ),
        migrations.AddField(
            model_name='companybalancesheet',
            name='oth_receiv',
            field=models.FloatField(blank=True, null=True, verbose_name='其他应收款'),
        ),
        migrations.AddField(
            model_name='companybalancesheet',
            name='payable_to_reinsurer',
            field=models.FloatField(blank=True, null=True, verbose_name='应付分保账款'),
        ),
        migrations.AddField(
            model_name='companybalancesheet',
            name='payables',
            field=models.FloatField(blank=True, null=True, verbose_name='应付款项'),
        ),
        migrations.AddField(
            model_name='companybalancesheet',
            name='payroll_payable',
            field=models.FloatField(blank=True, null=True, verbose_name='应付职工薪酬'),
        ),
        migrations.AddField(
            model_name='companybalancesheet',
            name='ph_invest',
            field=models.FloatField(blank=True, null=True, verbose_name='保户储金及投资款'),
        ),
        migrations.AddField(
            model_name='companybalancesheet',
            name='ph_pledge_loans',
            field=models.FloatField(blank=True, null=True, verbose_name='保户质押贷款'),
        ),
        migrations.AddField(
            model_name='companybalancesheet',
            name='pledge_borr',
            field=models.FloatField(blank=True, null=True, verbose_name='质押借款'),
        ),
        migrations.AddField(
            model_name='companybalancesheet',
            name='policy_div_payable',
            field=models.FloatField(blank=True, null=True, verbose_name='应付保单红利'),
        ),
        migrations.AddField(
            model_name='companybalancesheet',
            name='prec_metals',
            field=models.FloatField(blank=True, null=True, verbose_name='贵金属'),
        ),
        migrations.AddField(
            model_name='companybalancesheet',
            name='prem_receiv_adva',
            field=models.FloatField(blank=True, null=True, verbose_name='预收保费'),
        ),
        migrations.AddField(
            model_name='companybalancesheet',
            name='premium_receiv',
            field=models.FloatField(blank=True, null=True, verbose_name='应收保费'),
        ),
        migrations.AddField(
            model_name='companybalancesheet',
            name='prepayment',
            field=models.FloatField(blank=True, null=True, verbose_name='预付款项'),
        ),
        migrations.AddField(
            model_name='companybalancesheet',
            name='produc_bio_assets',
            field=models.FloatField(blank=True, null=True, verbose_name='生产性生物资产'),
        ),
        migrations.AddField(
            model_name='companybalancesheet',
            name='pur_resale_fa',
            field=models.FloatField(blank=True, null=True, verbose_name='买入返售金融资产'),
        ),
        migrations.AddField(
            model_name='companybalancesheet',
            name='r_and_d',
            field=models.FloatField(blank=True, null=True, verbose_name='研发支出'),
        ),
        migrations.AddField(
            model_name='companybalancesheet',
            name='receiv_financing',
            field=models.FloatField(blank=True, null=True, verbose_name='应收款项融资'),
        ),
        migrations.AddField(
            model_name='companybalancesheet',
            name='refund_cap_depos',
            field=models.FloatField(blank=True, null=True, verbose_name='存出资本保证金'),
        ),
        migrations.AddField(
            model_name='companybalancesheet',
            name='refund_depos',
            field=models.FloatField(blank=True, null=True, verbose_name='存出保证金'),
        ),
        migrations.AddField(
            model_name='companybalancesheet',
            name='reinsur_receiv',
            field=models.FloatField(blank=True, null=True, verbose_name='应收分保账款'),
        ),
        migrations.AddField(
            model_name='companybalancesheet',
            name='reinsur_res_receiv',
            field=models.FloatField(blank=True, null=True, verbose_name='应收分保合同准备金'),
        ),
        migrations.AddField(
            model_name='companybalancesheet',
            name='report_type',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='报表类型'),
        ),
        migrations.AddField(
            model_name='companybalancesheet',
            name='reser_lins_liab',
            field=models.FloatField(blank=True, null=True, verbose_name='寿险责任准备金'),
        ),
        migrations.AddField(
            model_name='companybalancesheet',
            name='reser_lthins_liab',
            field=models.FloatField(blank=True, null=True, verbose_name='长期健康险责任准备金'),
        ),
        migrations.AddField(
            model_name='companybalancesheet',
            name='reser_outstd_claims',
            field=models.FloatField(blank=True, null=True, verbose_name='未决赔款准备金'),
        ),
        migrations.AddField(
            model_name='companybalancesheet',
            name='reser_une_prem',
            field=models.FloatField(blank=True, null=True, verbose_name='未到期责任准备金'),
        ),
        migrations.AddField(
            model_name='companybalancesheet',
            name='rr_reins_lins_liab',
            field=models.FloatField(blank=True, null=True, verbose_name='应收分保寿险责任准备金'),
        ),
        migrations.AddField(
            model_name='companybalancesheet',
            name='rr_reins_lthins_liab',
            field=models.FloatField(blank=True, null=True, verbose_name='应收分保长期健康险责任准备金'),
        ),
        migrations.AddField(
            model_name='companybalancesheet',
            name='rr_reins_outstd_cla',
            field=models.FloatField(blank=True, null=True, verbose_name='应收分保未决赔款准备金'),
        ),
        migrations.AddField(
            model_name='companybalancesheet',
            name='rr_reins_une_prem',
            field=models.FloatField(blank=True, null=True, verbose_name='应收分保未到期责任准备金'),
        ),
        migrations.AddField(
            model_name='companybalancesheet',
            name='rsrv_insur_cont',
            field=models.FloatField(blank=True, null=True, verbose_name='保险合同准备金'),
        ),
        migrations.AddField(
            model_name='companybalancesheet',
            name='sett_rsrv',
            field=models.FloatField(blank=True, null=True, verbose_name='结算备付金'),
        ),
        migrations.AddField(
            model_name='companybalancesheet',
            name='sold_for_repur_fa',
            field=models.FloatField(blank=True, null=True, verbose_name='卖出回购金融资产款'),
        ),
        migrations.AddField(
            model_name='companybalancesheet',
            name='special_rese',
            field=models.FloatField(blank=True, null=True, verbose_name='专项储备'),
        ),
        migrations.AddField(
            model_name='companybalancesheet',
            name='specific_payables',
            field=models.FloatField(blank=True, null=True, verbose_name='专项应付款'),
        ),
        migrations.AddField(
            model_name='companybalancesheet',
            name='st_bonds_payable',
            field=models.FloatField(blank=True, null=True, verbose_name='应付短期债券'),
        ),
        migrations.AddField(
            model_name='companybalancesheet',
            name='st_borr',
            field=models.FloatField(blank=True, null=True, verbose_name='短期借款'),
        ),
        migrations.AddField(
            model_name='companybalancesheet',
            name='st_fin_payable',
            field=models.FloatField(blank=True, null=True, verbose_name='应付短期融资款'),
        ),
        migrations.AddField(
            model_name='companybalancesheet',
            name='surplus_rese',
            field=models.FloatField(blank=True, null=True, verbose_name='盈余公积金'),
        ),
        migrations.AddField(
            model_name='companybalancesheet',
            name='taxes_payable',
            field=models.FloatField(blank=True, null=True, verbose_name='应交税费'),
        ),
        migrations.AddField(
            model_name='companybalancesheet',
            name='time_deposits',
            field=models.FloatField(blank=True, null=True, verbose_name='定期存款'),
        ),
        migrations.AddField(
            model_name='companybalancesheet',
            name='total_assets',
            field=models.FloatField(blank=True, null=True, verbose_name='资产总计'),
        ),
        migrations.AddField(
            model_name='companybalancesheet',
            name='total_cur_assets',
            field=models.FloatField(blank=True, null=True, verbose_name='流动资产合计'),
        ),
        migrations.AddField(
            model_name='companybalancesheet',
            name='total_cur_liab',
            field=models.FloatField(blank=True, null=True, verbose_name='流动负债合计'),
        ),
        migrations.AddField(
            model_name='companybalancesheet',
            name='total_hldr_eqy_exc_min_int',
            field=models.FloatField(blank=True, null=True, verbose_name='股东权益合计(不含少数股东权益)'),
        ),
        migrations.AddField(
            model_name='companybalancesheet',
            name='total_hldr_eqy_inc_min_int',
            field=models.FloatField(blank=True, null=True, verbose_name='股东权益合计(含少数股东权益)'),
        ),
        migrations.AddField(
            model_name='companybalancesheet',
            name='total_liab',
            field=models.FloatField(blank=True, null=True, verbose_name='负债合计'),
        ),
        migrations.AddField(
            model_name='companybalancesheet',
            name='total_liab_hldr_eqy',
            field=models.FloatField(blank=True, null=True, verbose_name='负债及股东权益总计'),
        ),
        migrations.AddField(
            model_name='companybalancesheet',
            name='total_nca',
            field=models.FloatField(blank=True, null=True, verbose_name='非流动资产合计'),
        ),
        migrations.AddField(
            model_name='companybalancesheet',
            name='total_ncl',
            field=models.FloatField(blank=True, null=True, verbose_name='非流动负债合计'),
        ),
        migrations.AddField(
            model_name='companybalancesheet',
            name='total_share',
            field=models.FloatField(blank=True, null=True, verbose_name='期末总股本'),
        ),
        migrations.AddField(
            model_name='companybalancesheet',
            name='trad_asset',
            field=models.FloatField(blank=True, null=True, verbose_name='交易性金融资产'),
        ),
        migrations.AddField(
            model_name='companybalancesheet',
            name='trading_fl',
            field=models.FloatField(blank=True, null=True, verbose_name='交易性金融负债'),
        ),
        migrations.AddField(
            model_name='companybalancesheet',
            name='transac_seat_fee',
            field=models.FloatField(blank=True, null=True, verbose_name='交易席位费'),
        ),
        migrations.AddField(
            model_name='companybalancesheet',
            name='treasury_share',
            field=models.FloatField(blank=True, null=True, verbose_name='减:库存股'),
        ),
        migrations.AddField(
            model_name='companybalancesheet',
            name='undistr_porfit',
            field=models.FloatField(blank=True, null=True, verbose_name='未分配利润'),
        ),
        migrations.AddField(
            model_name='companybalancesheet',
            name='update_flag',
            field=models.CharField(blank=True, max_length=50, verbose_name='更新标识'),
        ),
        migrations.AddField(
            model_name='companybalancesheet',
            name='use_right_assets',
            field=models.FloatField(blank=True, null=True, verbose_name='使用权资产'),
        ),
        migrations.AddField(
            model_name='stocknamecodemap',
            name='balance_sheet_date',
            field=models.DateField(blank=True, null=True, verbose_name='财务指标下载日期'),
        ),
        migrations.AlterField(
            model_name='companybalancesheet',
            name='ts_code',
            field=models.CharField(blank=True, db_index=True, max_length=50, verbose_name='TS代码'),
        ),
    ]
