# Generated by Django 3.2.10 on 2022-03-05 03:07

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('stockmarket', '0046_auto_20220110_1943'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyfinindicators',
            name='pb',
            field=models.FloatField(blank=True, null=True, verbose_name='pb'),
        ),
        migrations.AddField(
            model_name='companyfinindicators',
            name='pe',
            field=models.FloatField(blank=True, null=True, verbose_name='pe'),
        ),
        migrations.AddField(
            model_name='companyfinindicators',
            name='pe_ttm',
            field=models.FloatField(blank=True, null=True, verbose_name='pe_ttm'),
        ),
        migrations.AddField(
            model_name='companyfinindicators',
            name='price',
            field=models.FloatField(blank=True, null=True, verbose_name='价格'),
        ),
        migrations.AddField(
            model_name='companyfinindicators',
            name='ps',
            field=models.FloatField(blank=True, null=True, verbose_name='ps'),
        ),
        migrations.AddField(
            model_name='companyfinindicators',
            name='ps_ttm',
            field=models.FloatField(blank=True, null=True, verbose_name='ps_ttm'),
        ),
        migrations.CreateModel(
            name='CompanyIndicatorCorrelation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('last_mod_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='最后更新时间')),
                ('ts_code', models.CharField(blank=True, db_index=True, max_length=50, verbose_name='TS代码')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='报告期')),
                ('a_indicator', models.FloatField(blank=True, db_index=True, null=True, verbose_name='计算指标')),
                ('correlation', models.FloatField(blank=True, null=True, verbose_name='关联度')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='company_correlation', to='stockmarket.stocknamecodemap')),
            ],
            options={
                'verbose_name': '指标关联度',
                'verbose_name_plural': '指标关联度',
                'ordering': ['-end_date'],
                'get_latest_by': 'id',
            },
        ),
    ]
