# Generated by Django 3.2.10 on 2022-03-05 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stockmarket', '0047_auto_20220305_1107'),
    ]

    operations = [
        migrations.RenameField(
            model_name='companyfinindicators',
            old_name='price',
            new_name='close',
        ),
    ]
