# Generated by Django 3.2.10 on 2022-03-06 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockmarket', '0049_companyfinindicators_total_mv'),
    ]

    operations = [
        migrations.AddField(
            model_name='stocknamecodemap',
            name='popdb2fin_date',
            field=models.DateField(blank=True, null=True, verbose_name='推送每日指标日期'),
        ),
    ]
