# Generated by Django 3.2.10 on 2022-04-20 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockmarket', '0050_stocknamecodemap_popdb2fin_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='stocknamecodemap',
            name='pop2eema_date',
            field=models.DateField(blank=True, null=True, verbose_name='推送加强ema指标日期(短线窥探)'),
        ),
    ]
