# Generated by Django 4.1 on 2022-09-14 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockmarket', '0051_stocknamecodemap_pop2eema_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='stocknamecodemap',
            name='hist_download_date_m',
            field=models.DateField(blank=True, null=True, verbose_name='月线下载日期'),
        ),
        migrations.AddField(
            model_name='stocknamecodemap',
            name='hist_download_date_w',
            field=models.DateField(blank=True, null=True, verbose_name='周线下载日期'),
        ),
    ]
