# Generated by Django 4.1 on 2022-09-14 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockmarket', '0052_stocknamecodemap_hist_download_date_m_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stocknamecodemap',
            name='pop2eema_date_w',
            field=models.DateField(blank=True, null=True, verbose_name='短线窥探W'),
        ),
        migrations.AlterField(
            model_name='stocknamecodemap',
            name='pop2eema_date',
            field=models.DateField(blank=True, null=True, verbose_name='短线窥探M'),
        ),
    ]
