# Generated by Django 4.1 on 2022-09-14 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockmarket', '0053_stocknamecodemap_pop2eema_date_w_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stocknamecodemap',
            name='pop2eema_date_m',
            field=models.DateField(blank=True, null=True, verbose_name='短线窥探M'),
        ),
        migrations.AlterField(
            model_name='stocknamecodemap',
            name='pop2eema_date',
            field=models.DateField(blank=True, null=True, verbose_name='短线窥探D'),
        ),
    ]
