# Generated by Django 3.0.2 on 2020-04-20 13:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tradeaccounts', '0001_initial'),
        ('investors', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('last_mod_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='最后更新时间')),
                ('market', models.CharField(choices=[('ZB', '主板'), ('ZXB', '中小板'), ('CYB', '创业板'), ('KCB', '科创板')], editable=False, max_length=10, verbose_name='股票市场')),
                ('stock_name', models.CharField(max_length=50, verbose_name='股票名称')),
                ('stock_code', models.CharField(max_length=50, verbose_name='股票代码')),
                ('direction', models.CharField(choices=[('b', '买入'), ('s', '卖出')], default='b', max_length=1, verbose_name='交易类型')),
                ('trade_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='交易时间')),
                ('price', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='交易价格')),
                ('sell_price', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='卖出价')),
                ('current_price', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='股票现价')),
                ('target_position', models.PositiveIntegerField(blank=True, default=100, null=True, verbose_name='目标仓位（股）')),
                ('board_lots', models.PositiveIntegerField(default=100, verbose_name='本次交易量(股)')),
                ('lots_remain', models.PositiveIntegerField(default=0, verbose_name='剩余持仓')),
                ('cash', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='交易现金额')),
                ('visible', models.CharField(choices=[('g', '公开'), ('s', '私密'), ('f', '仅好友')], default='s', max_length=1, verbose_name='可见性')),
                ('comment_status', models.CharField(choices=[('o', '打开'), ('c', '关闭')], default='c', max_length=1, verbose_name='评论状态')),
                ('views', models.PositiveIntegerField(default=0, verbose_name='浏览量')),
                ('is_liquadated', models.BooleanField(default=False, editable=False, verbose_name='是否已清仓')),
                ('rec_ref_number', models.CharField(blank=True, max_length=10, null=True, verbose_name='买入记录编号')),
                ('is_sold', models.BooleanField(default=False, verbose_name='是否已卖出')),
                ('sold_time', models.DateTimeField(blank=True, null=True, verbose_name='卖出时间')),
                ('created_or_mod_by', models.CharField(default='human', editable=False, max_length=50, verbose_name='创建人')),
                ('in_stock_positions', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='tradeaccounts.Positions', verbose_name='股票持仓')),
                ('sell_stock_refer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='stocktrade.Transactions', verbose_name='卖对应之买入')),
                ('strategy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='investors.TradeStrategy', verbose_name='策略')),
                ('trade_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tradeaccounts.TradeAccount', verbose_name='交易账户')),
                ('trader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='投资人')),
            ],
            options={
                'verbose_name': '交易记录',
                'verbose_name_plural': '交易记录',
                'ordering': ['-last_mod_time'],
                'get_latest_by': 'id',
            },
        ),
    ]
