# Generated by Django 3.0.2 on 2020-04-20 23:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stocktrade', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transactions',
            options={'get_latest_by': 'id', 'ordering': ['-last_mod_time'], 'verbose_name': '交易明细', 'verbose_name_plural': '交易明细'},
        ),
        migrations.RenameField(
            model_name='transactions',
            old_name='is_liquadated',
            new_name='is_liquidated',
        ),
    ]
